import { newProject,newLevel,parseProject,uid,inside,editorWalkable,moveInEditor,portalAt,exportEditorLevel,mergeEditorLevel,type EditorProject,type EditorAsset,type EditorLevel,type EditorObject,type EditorRegion,type LayerKind } from '../../shared/map-editor';
import { AnimationPlayer,normalizeAtlas,type Atlas } from './atlas';
import { imageAlpha,cropAlpha,opaqueMasksOverlap,type AlphaMask } from './occlusion';
import {readPNG,importPNGs,sliceTileset} from './map-editor-import';
import type { Motion } from '../../shared/world';
import {entity,entityKey,entityBounds,objectBounds,selectionBounds,groupMembers,translateEntities,duplicateEntities,alignEntities,capturePrefab,instantiatePrefab,gridStroke,exportAssetLibrary,mergeAssetLibrary,auditProject,exportRuntimeProject,type EntitySelection,type Alignment} from '../../shared/level-design';

const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const canvas=el<HTMLCanvasElement>('map-canvas'),viewport=el('viewport'),ctx=canvas.getContext('2d')!;
document.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement|HTMLTextAreaElement>('input,button,select,textarea').forEach(n=>n.disabled=true);
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Selection={kind:'object'|'region';id:string}|null;
let project:EditorProject,selected:Selection=null,activeLayer='',chosenAsset='',tool='select',ready=false,playing=false,player:Motion={x:0,y:0,direction:'south',moving:false};
let selections:EntitySelection[]=[],chosenPrefab='',clipboard:ReturnType<typeof capturePrefab>|null=null;
let lastMinimap=0;
let replacingPart:{assetId:string;partId:string}|null=null;
let view={x:0,y:0,zoom:1},draft:Array<{x:number;y:number}>=[],hover={x:0,y:0},space=false,last=performance.now();
let drag:{mode:'pan'|'selection'|'marquee'|'brush'|'erase'|'vertex'|'rect';start:{x:number;y:number};screen:{x:number;y:number};before:EditorProject;index?:number;origin?:any;additive?:boolean;seen?:Set<string>;lastPoint?:{x:number;y:number}}|null=null;
let savedTimer:ReturnType<typeof setTimeout>|undefined;
let saveQueue:Promise<void>=Promise.resolve();
let editView:{levelId:string;view:{x:number;y:number;zoom:number}}|null=null;
const undo:EditorProject[]=[],redo:EditorProject[]=[],keys=new Set<string>();
const images=new Map<string,{image:HTMLImageElement;mask:AlphaMask}>();
const thumbnails=new Map<string,string>();
const libraryFiles=new Set<string>();
let actorImage:HTMLImageElement,actorSourceMask:AlphaMask,atlas:Atlas,animation:AnimationPlayer;
const actorFrameMasks=new Map<string,AlphaMask>();
const level=():EditorLevel=>project.levels.find(l=>l.id===project.activeLevelId)!;
const layerName=(id:string)=>level().layers.find(l=>l.id===id)?.name??'';
const object=()=>selected?.kind==='object'?level().objects.find(o=>o.id===selected!.id):undefined;
const region=()=>selected?.kind==='region'?level().regions.find(r=>r.id===selected!.id):undefined;
function setSelection(items:EntitySelection[]):void {selections=[...new Map(items.filter(s=>entity(level(),s)).map(s=>[entityKey(s),s])).values()];selected=selections.at(-1)??null;}
function clearSelection():void {selections=[];selected=null;}
function choose(s:Selection,additive=false,individual=false):void {if(!s){if(!additive)clearSelection();return;}const members=individual?[s]:groupMembers(level(),s),keys=new Set(members.map(entityKey));setSelection(additive?(members.every(m=>selections.some(v=>entityKey(v)===entityKey(m)))?selections.filter(v=>!keys.has(entityKey(v))):[...selections,...members.filter(v=>entityKey(v)!==entityKey(s)),s]):[...members.filter(v=>entityKey(v)!==entityKey(s)),s]);}
const objectLayerLocked=(o:EditorObject)=>Boolean(level().layers.find(l=>l.id===o.layerId)?.locked||(project.assets.find(a=>a.id===o.assetId)?.parts.some(p=>p.cover)&&level().layers.find(l=>l.id===o.coverLayerId)?.locked));
const status=(s:string)=>{el('status').textContent=s;};
const snap=(n:number)=>Math.round(n/Number(el<HTMLSelectElement>('snap').value))*Number(el<HTMLSelectElement>('snap').value);
const world=(e:{clientX:number;clientY:number})=>{const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left-view.x)/view.zoom,y:(e.clientY-b.top-view.y)/view.zoom};};
const snapped=(p:{x:number;y:number})=>({x:snap(p.x),y:snap(p.y)});
const image=async(file:string)=>{if(images.has(file))return;const img=new Image();img.src=file;await img.decode();images.set(file,{image:img,mask:imageAlpha(img)});};
async function loadAssets(p=project):Promise<void>{for(const a of p.assets)for(const part of a.parts){if(part.file.startsWith('/assets/map-kit/')&&!libraryFiles.has(part.file))throw new Error(`Asset cũ đã xóa khỏi thư viện: ${a.name}. Bản lưu vẫn được giữ; cần PNG mới để mở lại.`);}await Promise.all(p.assets.flatMap(a=>a.parts.map(p=>image(p.file))));for(const a of p.assets){for(const part of a.parts){const i=images.get(part.file)!.image;if(i.width!==a.width||i.height!==a.height)throw new Error(`Cỡ PNG không khớp: ${a.name}`);}if(a.parts.length>1){const c=document.createElement('canvas');c.width=a.width;c.height=a.height;for(const part of a.parts)c.getContext('2d')!.drawImage(images.get(part.file)!.image,0,0);thumbnails.set(a.id,c.toDataURL());}}}
function localSave():void {
  try{localStorage.setItem(`game-solo-map-editor:${project.id}`,JSON.stringify(project));localStorage.setItem('game-solo-map-editor-last',project.id);}
  catch{status('Bản nháp vượt bộ nhớ trình duyệt. Bấm Lưu dự án hoặc Xuất JSON để giữ dữ liệu.');}
}
function changed(before:EditorProject):void {
  try{project=parseProject(project);}catch(error){project=before;status(String(error));ui();return;}
  el('issues').innerHTML='<p class="hint">Dữ liệu đã đổi. Bấm Kiểm tra để cập nhật kết quả.</p>';undo.push(before);if(undo.length>40)undo.shift();redo.length=0;
  clearTimeout(savedTimer);savedTimer=setTimeout(localSave,350);ui();status('Bản nháp đã sửa · Ctrl+S để lưu vào dự án.');
}
function edit(fn:()=>void):void {if(playing){status('Dừng Test để chỉnh map.');return;}const before=structuredClone(project);try{fn();changed(before);}catch(error){project=before;clearSelection();ui();status(String(error));}}
function fit():void {const l=level();view.zoom=Math.min(1,(viewport.clientWidth-60)/l.width,(viewport.clientHeight-60)/l.height);view.zoom=Math.max(.25,view.zoom);view.x=(viewport.clientWidth-l.width*view.zoom)/2;view.y=(viewport.clientHeight-l.height*view.zoom)/2;el<HTMLInputElement>('zoom').value=String(Math.round(view.zoom*100)/100);}
function zoomTo(z:number,p={x:viewport.clientWidth/2,y:viewport.clientHeight/2}):void {const wx=(p.x-view.x)/view.zoom,wy=(p.y-view.y)/view.zoom;view.zoom=Math.max(.25,Math.min(4,z));view.x=p.x-wx*view.zoom;view.y=p.y-wy*view.zoom;el<HTMLInputElement>('zoom').value=String(Math.round(view.zoom*100)/100);}
function setTool(value:string):void {if(playing)return;tool=value;draft=[];document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));status(tool==='place'?'Bấm vào map để đặt asset; Esc trở lại chọn.':tool.endsWith('poly')?'Bấm các đỉnh, Enter để hoàn tất; Esc hủy.':'Kéo để chỉnh; Space hoặc chuột giữa để di chuyển khung.');}
function activate(id:string):void {project.activeLevelId=id;clearSelection();activeLayer=level().layers.find(l=>l.kind==='depth')?.id??level().layers[0].id;draft=[];keys.clear();if(playing){player={...level().spawn,direction:'south',moving:false};}fit();ui();localSave();}
function download(name:string,value:unknown):void {const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function savedList():Promise<void>{
  const select=el<HTMLSelectElement>('saved-projects');select.replaceChildren(new Option('Mở bản lưu…',''));
  try{const r=await fetch('/api/map-editor/projects');if(r.ok){for(const p of (await r.json()).projects)select.add(new Option(`${p.name} · dự án`,p.id));}}catch{/* Browser drafts still work without the local API. */}
  for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)!;if(!key.startsWith('game-solo-map-editor:'))continue;try{const p=parseProject(JSON.parse(localStorage.getItem(key)!));select.add(new Option(`${p.name} · nháp trình duyệt`,`draft:${p.id}`));}catch{/* Preserve invalid old drafts. */}}
}
function save():Promise<void>{localSave();const snapshot=structuredClone(project);status('Đang chờ lưu vào dự án…');const work=async()=>{try{const r=await fetch(`/api/map-editor/projects/${snapshot.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});const result=await r.json();if(!r.ok)throw new Error(result.error);if(project.id===snapshot.id)status(JSON.stringify(project)===JSON.stringify(snapshot)?`Đã lưu: ${result.path}`:'Đã lưu phiên bản vừa gửi; còn thay đổi mới chưa lưu.');await savedList();}catch(error){status(`Chưa lưu được file dự án: ${String(error)}. Xuất JSON để lưu bản này.`);}};saveQueue=saveQueue.then(work,work);return saveQueue;}
function palette():void {
  const search=el<HTMLInputElement>('search').value.toLocaleLowerCase('vi'),category=el<HTMLSelectElement>('asset-category').value;
  el('palette').innerHTML=project.assets.filter(a=>a.name.toLocaleLowerCase('vi').includes(search)&&(!category||(a.category??'other')===category)).map(a=>`<button class="asset-card ${a.id===chosenAsset?'selected':''}" draggable="true" data-asset="${esc(a.id)}" title="${a.width} × ${a.height}"><img draggable="false" loading="lazy" src="${esc(thumbnails.get(a.id)??a.parts[0].file)}" alt="" /><span>${esc(a.name)}</span></button>`).join('')||`<p class="hint">${project.assets.length?'Không có asset khớp từ khóa.':'Thư viện trống. Nhập PNG riêng để bắt đầu bộ map mới.'}</p>`;
}
const inputField=(name:string,label:string,value:unknown,type='text',extra='')=>`<label class="form-row">${label}<input data-field="${name}" type="${type}" value="${esc(value)}" ${extra} /></label>`;
const selectField=(name:string,label:string,value:string,options:Array<[string,string]>)=>`<label class="form-row">${label}<select data-field="${name}">${options.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
function inspector():void {
  const o=object(),r=region(),l=level();let html='';
  if(selections.length>1){const b=selectionBounds(project,l,selections);html=`<p>${selections.length} đối tượng / vùng đang chọn.</p>`+inputField('selectionX','X · mép trái',b.left,'number')+inputField('selectionY','Y · mép trên',b.top,'number')+'<p class="hint">Kéo cả cụm hoặc dùng căn chỉnh/nhóm trên thanh công cụ. Alt+bấm để chọn riêng một thành phần.</p>';}else if(o){html=inputField('name','Tên đối tượng',o.name)+`<div class="form-pair">${inputField('x','X · điểm chân',o.x,'number')}${inputField('y','Y · điểm chân',o.y,'number')}</div>`+inputField('scale','Tỷ lệ',o.scale,'number','min=".1" max="4" step=".1"')+inputField('opacity','Độ hiện',o.opacity,'number','min="0" max="1" step=".05"')+selectField('layerId','Layer thân/vật',o.layerId,l.layers.filter(l=>l.kind!=='regions').map(l=>[l.id,l.name]))+selectField('coverLayerId','Layer tán/mái',o.coverLayerId,l.layers.filter(l=>l.kind==='cover').map(l=>[l.id,l.name]))+selectField('flipX','Lật ngang',String(o.flipX),[['false','Không'],['true','Có']])+selectField('locked','Khóa đối tượng',String(o.locked),[['false','Không'],['true','Có']]);}
  else if(r){html=inputField('name','Tên vùng',r.name)+selectField('kind','Loại vùng',r.kind,[['walk','Vùng đi'],['block','Vùng chặn'],['portal','Cửa nối level']])+selectField('layerId','Layer dữ liệu',r.layerId,l.layers.filter(l=>l.kind==='regions').map(l=>[l.id,l.name]))+selectField('enabled','Hoạt động',String(r.enabled),[['true','Có'],['false','Không']])+`<label class="form-row">Các đỉnh · x,y mỗi dòng<textarea data-field="points">${r.points.map(p=>`${p.x},${p.y}`).join('\n')}</textarea></label><p class="hint">Kéo điểm để sửa. Shift+bấm cạnh để thêm đỉnh; Alt+bấm điểm để xóa.</p>`;
    if(r.kind==='portal')html+=selectField('targetLevelId','Level đích',r.targetLevelId,[['','Chưa chọn'],...project.levels.map(l=>[l.id,l.name] as [string,string])])+inputField('targetX','X đến · để trống dùng spawn',r.target?.x??'','number')+inputField('targetY','Y đến',r.target?.y??'','number');
  }else {html=inputField('levelName','Tên level',l.name)+`<div class="form-pair">${inputField('width','Rộng',l.width,'number','min="64" max="8192"')}${inputField('height','Cao',l.height,'number','min="64" max="8192"')}</div>`+inputField('background','Màu nền',l.background,'color')+selectField('walkPolicy','Luật đi',l.walkPolicy,[['full','Đi trong toàn level, trừ vùng chặn'],['regions','Chỉ đi trong vùng đi đã vẽ']])+`<div class="form-pair">${inputField('spawnX','Spawn X',l.spawn.x,'number')}${inputField('spawnY','Spawn Y',l.spawn.y,'number')}</div>`;
    const layer=l.layers.find(x=>x.id===activeLayer);if(layer)html+='<h2>Layer đang chọn</h2>'+inputField('layerName','Tên layer',layer.name)+selectField('layerKind','Cách hiển thị',layer.kind,[['ground','Nền'],['decor','Trang trí thấp'],['depth','Theo chân'],['cover','Tán/mái · theo chân'],['regions','Dữ liệu vùng']]);
  }
  if(o&&selections.length===1){const a=project.assets.find(a=>a.id===o.assetId)!,p=o.pivot??a.pivot;html+=`<div class="form-pair">${inputField('pivotX','Pivot X · trong PNG',p.x,'number')}${inputField('pivotY','Pivot Y · trong PNG',p.y,'number')}</div><p class="hint">Pivot là điểm đặt và điểm chân để xếp lớp. Các part cùng nhóm dùng chung pivot.</p>`;}
  el('inspector').innerHTML=html;el('inspector').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-field]').forEach(n=>n.disabled=playing);
  const locked=selections.some(s=>{const item=entity(l,s);return s.kind==='object'?Boolean(item&&((item as EditorObject).locked||objectLayerLocked(item as EditorObject))):Boolean(l.layers.find(x=>x.id===item?.layerId)?.locked);});
  if(locked)el('inspector').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-field]').forEach(n=>{if(n.dataset.field!=='locked'||o&&objectLayerLocked(o))n.disabled=true;});
}
function ui():void {
  if(!project)return;setSelection(selections);const l=level();el<HTMLInputElement>('project-name').value=project.name;
  el<HTMLSelectElement>('level').replaceChildren(...project.levels.map(x=>new Option(x.name,x.id)));el<HTMLSelectElement>('level').value=l.id;
  el('layers').innerHTML=[...l.layers].reverse().map(x=>`<div class="layer-row ${x.id===activeLayer?'selected':''}" data-layer="${x.id}"><button data-layer-select="${x.id}">${esc(x.name)}</button>${(['visible','locked','enabled'] as const).map((key,i)=>`<label title="${['Hiện trong editor','Khóa sửa','Hoạt động trong Test/xuất'][i]}"><input type="checkbox" data-layer-flag="${key}" data-id="${x.id}" ${x[key]?'checked':''} />${['👁','🔒','✓'][i]}</label>`).join('')}</div>`).join('');
  el('entities').innerHTML=[...l.objects.map(o=>({id:o.id,kind:'object',name:o.name})),...l.regions.map(r=>({id:r.id,kind:'region',name:`${r.kind==='block'?'⛔':r.kind==='portal'?'↗':'◇'} ${r.name}`}))].map(x=>`<button class="entity ${selections.some(s=>s.id===x.id)?'selected':''}" data-entity="${x.id}" data-kind="${x.kind}">${esc(x.name)}</button>`).join('')||'<p class="hint">Level trống. Kéo asset vào khung để bắt đầu.</p>';
  el('flows').innerHTML=project.levels.flatMap(a=>a.regions.filter(r=>r.kind==='portal').map(r=>{const dest=project.levels.find(l=>l.id===r.targetLevelId);return `<div class="flow ${dest?'':'warning'}">${esc(a.name)} → ${esc(dest?.name??'chưa chọn đích')}<br />${esc(r.name)} · ${r.enabled?'hoạt động':'tắt'}</div>`;})).join('')||'<p class="hint">Chưa có cửa nối level.</p>';
  el<HTMLButtonElement>('undo').disabled=!undo.length||playing;el<HTMLButtonElement>('redo').disabled=!redo.length||playing;
  el('play').textContent=playing?'■ Dừng Test':'▶ Test map';document.body.classList.toggle('testing',playing);el('mode-label').textContent=playing?'TEST · WASD / mũi tên · E qua cửa':`BIÊN TẬP · ${l.name}`;
  el('layers').querySelectorAll<HTMLInputElement>('input').forEach(n=>n.disabled=playing);
  for(const id of ['project-name','new-project','add-level','clone-level','delete-level','duplicate','remove','add-layer','layer-up','layer-down','delete-layer','import-asset','import-project','import-level'])el<HTMLInputElement|HTMLButtonElement>(id).disabled=playing;
  el('counts').textContent=`${l.width} × ${l.height} · ${l.objects.length} vật · ${l.regions.length} vùng · ${selections.length} chọn`;palette();inspector();engineUi();
}
function stamp(assetId:string,p:{x:number;y:number}):EditorObject|null {
  const a=project.assets.find(x=>x.id===assetId);if(!a||level().objects.length>=10000)return null;
  const current=level().layers.find(l=>l.id===activeLayer&&l.kind!=='regions'),base=current??level().layers.find(l=>l.kind===(a.defaultLayer??'depth')),cover=level().layers.find(l=>l.kind==='cover');
  if(!base||!cover||base.locked||(a.parts.some(p=>p.cover)&&cover.locked)){status('Cần layer đặt và Tán/Mái đã mở khóa.');return null;}
  const o:EditorObject={id:uid(),name:a.name,assetId:a.id,layerId:base.id,coverLayerId:cover.id,...p,scale:1,flipX:false,opacity:1,locked:false};level().objects.push(o);activeLayer=base.id;return o;
}
function place(assetId:string,p:{x:number;y:number}):void {if(playing)return;edit(()=>{const o=stamp(assetId,snapped(p));if(o)choose({kind:'object',id:o.id});});}
function addRegion(points:Array<{x:number;y:number}>):void {
  const l=level(),layer=l.layers.find(l=>l.id===activeLayer&&l.kind==='regions')??l.layers.find(l=>l.kind==='regions');if(!layer||layer.locked){status('Cần layer Vùng hoạt động đã mở khóa.');return;}
  const kind=tool.startsWith('walk')?'walk':tool.startsWith('portal')?'portal':'block';
  edit(()=>{const r:EditorRegion={id:uid(),name:kind==='walk'?'Vùng đi':kind==='block'?'Vùng chặn':'Cửa nối',kind,layerId:layer.id,points,enabled:true,targetLevelId:'',target:null};l.regions.push(r);choose({kind:'region',id:r.id});activeLayer=layer.id;});
}
const bounds=objectBounds;
function selectionCandidates():EntitySelection[] {const l=level(),solo=el<HTMLInputElement>('solo-layer').checked,visible=(id:string)=>l.layers.some(v=>v.id===id&&v.visible&&(!solo||id===activeLayer));
  const items:EntitySelection[]=[...l.objects.filter(o=>{const a=project.assets.find(a=>a.id===o.assetId);return !o.locked&&!objectLayerLocked(o)&&a?.parts.some(p=>visible(p.cover?o.coverLayerId:o.layerId));}).map(o=>({kind:'object' as const,id:o.id})),...l.regions.filter(r=>el<HTMLInputElement>('show-regions').checked&&visible(r.layerId)&&!l.layers.find(v=>v.id===r.layerId)?.locked).map(r=>({kind:'region' as const,id:r.id}))];
  return items.filter(s=>groupMembers(l,s).every(m=>{const item=entity(l,m)!;return m.kind==='object'?!((item as EditorObject).locked||objectLayerLocked(item as EditorObject)):!l.layers.find(v=>v.id===item.layerId)?.locked;}));
}
function hit(p:{x:number;y:number}):Selection {
  const l=level();if(el<HTMLInputElement>('show-regions').checked)for(const r of [...l.regions].reverse()){const layer=l.layers.find(x=>x.id===r.layerId);if(layer?.visible&&!layer.locked&&(!el<HTMLInputElement>('solo-layer').checked||layer.id===activeLayer)&&inside(p,r.points))return {kind:'region',id:r.id};}
  if(p.x<0||p.y<0||p.x>l.width||p.y>l.height)return null;
  const rows=l.objects.flatMap((o,index)=>{if(objectLayerLocked(o)||o.locked)return [];const a=project.assets.find(a=>a.id===o.assetId)!;return a.parts.flatMap(part=>{const layer=l.layers.find(x=>x.id===(part.cover?o.coverLayerId:o.layerId));if(!layer?.visible||(el<HTMLInputElement>('solo-layer').checked&&layer.id!==activeLayer))return [];return [{o,a,part,index,band:layer.kind==='ground'?0:layer.kind==='decor'?1:2,order:l.layers.indexOf(layer),cover:part.cover||layer.kind==='cover'}];});});
  rows.sort((a,b)=>a.band-b.band||(a.band===2?a.o.y-b.o.y||Number(a.cover)-Number(b.cover):a.order-b.order)||a.index-b.index).reverse();
  for(const {o,a,part} of rows){const b=bounds(o,a);let x=Math.floor((p.x-b.left)/o.scale);const y=Math.floor((p.y-b.top)/o.scale);if(o.flipX)x=a.width-1-x;if(x<0||y<0||x>=a.width||y>=a.height)continue;if((images.get(part.file)?.mask.alpha[y*a.width+x]??0)>48)return {kind:'object',id:o.id};}
  return null;
}
canvas.addEventListener('dragover',e=>e.preventDefault());canvas.addEventListener('drop',e=>{e.preventDefault();place(e.dataTransfer?.getData('application/x-map-asset')??'',world(e));viewport.focus();});
el('palette').addEventListener('dragstart',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-asset]');if(b){(e as DragEvent).dataTransfer?.setData('application/x-map-asset',b.dataset.asset!);}});
el('palette').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-asset]');if(b){chosenAsset=b.dataset.asset!;chosenPrefab='';const a=project.assets.find(a=>a.id===chosenAsset)!;if(a.defaultLayer)activeLayer=level().layers.find(l=>l.kind===a.defaultLayer)?.id??activeLayer;setTool(['brush','paint-rect','erase'].includes(tool)?tool:'place');ui();}});
function brushStep():number {return Math.max(1,Math.min(2048,Number(el<HTMLInputElement>('brush-step').value)||32));}
function paintCell(p:{x:number;y:number}):void {const a=project.assets.find(a=>a.id===chosenAsset);if(!a)return;const base=level().layers.find(l=>l.id===activeLayer&&l.kind!=='regions')??level().layers.find(l=>l.kind===(a.defaultLayer??'depth')),cover=level().layers.find(l=>l.kind==='cover');if(!base||base.locked||!cover||(a.parts.some(p=>p.cover)&&cover.locked))return;
  const same=level().objects.filter(o=>o.layerId===base.id&&o.x===p.x&&o.y===p.y);if(same.some(o=>o.assetId===chosenAsset))return;
  if(a.category==='terrain'){const previous=same.filter(o=>project.assets.find(a=>a.id===o.assetId)?.category==='terrain');if(previous.some(o=>o.locked||objectLayerLocked(o)||o.groupId))return;const ids=new Set(previous.map(o=>o.id));level().objects=level().objects.filter(o=>!ids.has(o.id));}
  stamp(chosenAsset,p);
}
function brushPath(to:{x:number;y:number}):void {if(!drag||!['brush','erase'].includes(drag.mode))return;const step=brushStep();for(const p of gridStroke(drag.lastPoint??drag.start,to,step)){const key=`${p.x},${p.y}`;if(drag.seen!.has(key)||p.x<0||p.y<0||p.x>=level().width||p.y>=level().height)continue;drag.seen!.add(key);if(drag.mode==='erase'){level().objects=level().objects.filter(o=>o.layerId!==activeLayer||o.locked||objectLayerLocked(o)||o.groupId||Math.round(o.x/step)!==Math.round(p.x/step)||Math.round(o.y/step)!==Math.round(p.y/step));}else paintCell(p);}drag.lastPoint=to;}
canvas.addEventListener('pointerdown',e=>{
  if(!ready)return;viewport.focus();const p=world(e);hover=p;canvas.setPointerCapture(e.pointerId);
  if(e.button===1||space||tool==='pan'){e.preventDefault();drag={mode:'pan',start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),origin:{...view}};return;}
  if(e.button!==0||playing)return;
  if(tool==='place'){place(chosenAsset,p);return;}
  if(tool==='prefab'){const f=project.prefabs?.find(f=>f.id===chosenPrefab);if(f)edit(()=>setSelection(instantiatePrefab(project,level(),f,snapped(p))));return;}
  if(tool==='brush'||tool==='erase'){if(tool==='brush'&&!chosenAsset){status('Chọn asset trước khi dùng cọ.');return;}if(level().layers.find(l=>l.id===activeLayer)?.locked){status('Layer đang khóa.');return;}clearSelection();drag={mode:tool,start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),seen:new Set(),lastPoint:p};brushPath(p);return;}
  if(tool==='spawn'){edit(()=>level().spawn=snapped(p));return;}
  if(tool.endsWith('poly')){draft.push(snapped(p));return;}
  if(tool.endsWith('rect')){drag={mode:'rect',start:snapped(p),screen:{x:e.clientX,y:e.clientY},before:structuredClone(project)};return;}
  const r=region(),layer=r&&level().layers.find(l=>l.id===r.layerId),vertex=r&&selections.length===1&&!layer?.locked?r.points.findIndex(v=>Math.hypot(v.x-p.x,v.y-p.y)<10/view.zoom):-1;
  if(r&&vertex>=0&&e.altKey){if(r.points.length<=3){status('Đa giác cần ít nhất 3 đỉnh.');return;}edit(()=>r.points.splice(vertex,1));return;}
  if(r&&selections.length===1&&!layer?.locked&&e.shiftKey&&vertex<0){let edge=-1,best=10/view.zoom;for(let i=0;i<r.points.length;i++){const a=r.points[i],b=r.points[(i+1)%r.points.length],dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1))),distance=Math.hypot(p.x-a.x-dx*t,p.y-a.y-dy*t);if(distance<best){edge=i;best=distance;}}if(edge>=0){edit(()=>r.points.splice(edge+1,0,snapped(p)));return;}}
  if(r&&vertex>=0){drag={mode:'vertex',start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),index:vertex};return;}
  const found=hit(p),additive=e.shiftKey||e.ctrlKey||e.metaKey;
  if(!found){if(!additive)clearSelection();drag={mode:'marquee',start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),additive,origin:[...selections]};ui();return;}
  if(additive||!selections.some(s=>entityKey(s)===entityKey(found)))choose(found,additive,e.altKey);else if(e.altKey)choose(found,false,true);
  activeLayer=object()?.layerId??region()?.layerId??activeLayer;ui();if(!selections.length||!canEditSelection())return;
  drag={mode:'selection',start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),origin:structuredClone(level())};
});
canvas.addEventListener('pointermove',e=>{const p=world(e);hover=p;el('coordinates').textContent=`${Math.round(p.x)}, ${Math.round(p.y)} · ${view.zoom.toFixed(2)}×`;if(!drag)return;
  if(drag.mode==='pan'){view.x=drag.origin.x+e.clientX-drag.screen.x;view.y=drag.origin.y+e.clientY-drag.screen.y;return;}
  if(drag.mode==='selection'){for(const s of selections){const source=entity(drag.origin,s)!,dest=entity(level(),s)!;if(s.kind==='object'){const o=dest as EditorObject,v=source as EditorObject;o.x=v.x;o.y=v.y;}else (dest as EditorRegion).points=structuredClone((source as EditorRegion).points);}translateEntities(level(),selections,snap(p.x-drag.start.x),snap(p.y-drag.start.y));}
  if(drag.mode==='vertex')region()!.points[drag.index!]=snapped(p);
  if(drag.mode==='brush'||drag.mode==='erase')brushPath(p);
});
canvas.addEventListener('pointerup',e=>{if(!drag)return;const d=drag,p=world(e);drag=null;
  if(d.mode==='marquee'){const left=Math.min(d.start.x,p.x),top=Math.min(d.start.y,p.y),right=Math.max(d.start.x,p.x),bottom=Math.max(d.start.y,p.y);if(right-left>3||bottom-top>3){const candidates=selectionCandidates();const found=candidates.filter(s=>{const b=entityBounds(project,level(),s);return b.left<right&&b.left+b.w>left&&b.top<bottom&&b.top+b.h>top;}).flatMap(s=>groupMembers(level(),s));setSelection([...(d.additive?d.origin:[]),...found]);}ui();return;}
  if(d.mode==='rect'){const a=d.start,b=snapped(p);if(tool==='paint-rect'){const step=brushStep(),left=Math.ceil(Math.min(a.x,b.x)/step)*step,top=Math.ceil(Math.min(a.y,b.y)/step)*step,right=Math.floor(Math.max(a.x,b.x)/step)*step,bottom=Math.floor(Math.max(a.y,b.y)/step)*step,count=(1+(right-left)/step)*(1+(bottom-top)/step);if(!chosenAsset){status('Chọn asset trước khi tô ô.');return;}if(count>2000){status('Mỗi lượt tô tối đa 2000 ô. Chia vùng nhỏ hơn.');return;}edit(()=>{for(let y=top;y<=bottom;y+=step)for(let x=left;x<=right;x+=step)if(x>=0&&y>=0&&x<level().width&&y<level().height)paintCell({x,y});});}
    else if(Math.abs(a.x-b.x)>=4&&Math.abs(a.y-b.y)>=4)addRegion([{x:a.x,y:a.y},{x:b.x,y:a.y},{x:b.x,y:b.y},{x:a.x,y:b.y}]);}
  else if(d.mode!=='pan'&&JSON.stringify(d.before.levels)!==JSON.stringify(project.levels))changed(d.before);ui();
});
canvas.addEventListener('pointercancel',()=>{if(drag&&drag.mode!=='pan'&&drag.mode!=='marquee')project=drag.before;drag=null;ui();});
canvas.addEventListener('wheel',e=>{e.preventDefault();const b=canvas.getBoundingClientRect();zoomTo(view.zoom*(e.deltaY<0?1.15:1/1.15),{x:e.clientX-b.left,y:e.clientY-b.top});},{passive:false});
const finish=()=>{if(draft.length>=3){addRegion([...draft]);draft=[];}else status('Cần ít nhất3 đỉnh.');};
el('finish-polygon').addEventListener('click',finish);document.querySelectorAll<HTMLElement>('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool!)));
function canEditSelection():boolean {for(const s of selections){const item=entity(level(),s);if(s.kind==='object'&&item&&((item as EditorObject).locked||objectLayerLocked(item as EditorObject))||s.kind==='region'&&item&&level().layers.find(l=>l.id===item.layerId)?.locked){status('Có đối tượng hoặc layer đang khóa. Mở khóa trước khi sửa cả lựa chọn.');return false;}}return true;}
function remove():void {if(!selections.length||!canEditSelection())return;edit(()=>{const objects=new Set(selections.filter(s=>s.kind==='object').map(s=>s.id)),regions=new Set(selections.filter(s=>s.kind==='region').map(s=>s.id));level().objects=level().objects.filter(o=>!objects.has(o.id));level().regions=level().regions.filter(r=>!regions.has(r.id));clearSelection();});}
function duplicate():void {if(!selections.length||!canEditSelection())return;edit(()=>setSelection(duplicateEntities(level(),selections)));}
function history(back:boolean):void {if(playing)return;el('issues').innerHTML='<p class="hint">Bấm Kiểm tra để cập nhật sau undo/redo.</p>';const from=back?undo:redo,to=back?redo:undo,p=from.pop();if(p){to.push(structuredClone(project));project=p;clearSelection();if(!level().layers.some(l=>l.id===activeLayer))activeLayer=level().layers.find(l=>l.kind==='depth')?.id??level().layers[0].id;ui();localSave();void loadAssets();}}
function testMode():void {if(playing){playing=false;keys.clear();if(editView?.levelId===level().id){view={...editView.view};el<HTMLInputElement>('zoom').value=String(Math.round(view.zoom*100)/100);}else fit();el<HTMLInputElement>('show-regions').checked=true;ui();status('Trở lại biên tập.');return;}if(!editorWalkable(level(),level().spawn)){status('Spawn đang bị chặn hoặc chưa có vùng đi. Chỉnh Spawn / vẽ vùng đi trước khi Test.');return;}editView={levelId:level().id,view:{...view}};view.zoom=1;el<HTMLInputElement>('zoom').value='1';playing=true;clearSelection();draft=[];player={...level().spawn,direction:'south',moving:false};animation.set('stand','south');keys.clear();el<HTMLInputElement>('show-regions').checked=false;ui();viewport.focus();status('WASD / mũi tên để đi; E qua cửa nối; Esc dừng.');}
function traverse():void {const result=portalAt(project,level(),player);if(!result){status('Không ở trong cửa hợp lệ, hoặc level đích/vị trí đến chưa đi được.');return;}project.activeLevelId=result.level.id;player={...result.point,direction:player.direction,moving:false};ui();status(`Đã qua cửa: ${result.level.name}`);}
el('play').addEventListener('click',testMode);el('remove').addEventListener('click',remove);el('duplicate').addEventListener('click',duplicate);el('undo').addEventListener('click',()=>history(true));el('redo').addEventListener('click',()=>history(false));
el('fit').addEventListener('click',fit);el('native').addEventListener('click',()=>zoomTo(1));el<HTMLInputElement>('zoom').addEventListener('change',()=>zoomTo(Number(el<HTMLInputElement>('zoom').value)));
el<HTMLSelectElement>('level').addEventListener('change',()=>{const select=el<HTMLSelectElement>('level'),next=project.levels.find(l=>l.id===select.value)!;if(playing&&!editorWalkable(next,next.spawn)){select.value=project.activeLevelId;status('Spawn của level này chưa đi được. Dừng Test để chỉnh.');return;}activate(select.value);});
el('add-level').addEventListener('click',()=>edit(()=>{const l=newLevel(`Level ${project.levels.length+1}`);project.levels.push(l);project.activeLevelId=l.id;clearSelection();activeLayer=l.layers[2].id;fit();}));
el('clone-level').addEventListener('click',()=>edit(()=>{const l=structuredClone(level()),old=l.id,ids=new Map(l.layers.map(x=>[x.id,uid()]));l.id=uid();l.name+=' (bản sao)';for(const layer of l.layers)layer.id=ids.get(layer.id)!;for(const o of l.objects){o.id=uid();o.layerId=ids.get(o.layerId)!;o.coverLayerId=ids.get(o.coverLayerId)!;}for(const r of l.regions){r.id=uid();r.layerId=ids.get(r.layerId)!;if(r.targetLevelId===old)r.targetLevelId=l.id;}project.levels.push(l);project.activeLevelId=l.id;clearSelection();activeLayer=l.layers[2]?.id??l.layers[0].id;}));
el('delete-level').addEventListener('click',()=>{if(project.levels.length<2){status('Dự án cần ít nhất một level.');return;}edit(()=>{const id=level().id;project.levels=project.levels.filter(l=>l.id!==id);project.activeLevelId=project.levels[0].id;clearSelection();activeLayer=level().layers[2]?.id??level().layers[0].id;for(const l of project.levels)for(const r of l.regions)if(r.targetLevelId===id)r.targetLevelId='';fit();});});
el('layers').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-layer-select]');if(b){activeLayer=b.dataset.layerSelect!;clearSelection();ui();}});
el('layers').addEventListener('change',e=>{const n=e.target as HTMLInputElement;if(n.dataset.layerFlag)edit(()=>{const l=level().layers.find(l=>l.id===n.dataset.id)!;l[n.dataset.layerFlag as 'visible'|'locked'|'enabled']=n.checked;});});
el('add-layer').addEventListener('click',()=>edit(()=>{const l={id:uid(),name:'Layer mới',kind:'depth' as LayerKind,visible:true,locked:false,enabled:true};level().layers.push(l);activeLayer=l.id;clearSelection();}));
for(const[id,delta]of [['layer-up',1],['layer-down',-1]] as const)el(id).addEventListener('click',()=>edit(()=>{const list=level().layers,i=list.findIndex(l=>l.id===activeLayer),j=i+delta;if(j>=0&&j<list.length)[list[i],list[j]]=[list[j],list[i]];}));
el('delete-layer').addEventListener('click',()=>{if(level().objects.some(o=>o.layerId===activeLayer||o.coverLayerId===activeLayer)||level().regions.some(r=>r.layerId===activeLayer)||level().layers.length===1){status('Layer còn đối tượng/vùng tham chiếu. Chuyển chúng sang layer khác trước.');return;}edit(()=>{level().layers=level().layers.filter(l=>l.id!==activeLayer);activeLayer=level().layers[0].id;});});
el('entities').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-entity]');if(b){choose({kind:b.dataset.kind as 'object'|'region',id:b.dataset.entity!},(e as MouseEvent).shiftKey||(e as MouseEvent).ctrlKey,(e as MouseEvent).altKey);activeLayer=object()?.layerId??region()?.layerId??activeLayer;setTool('select');ui();}});
el('inspector').addEventListener('change',e=>{const n=e.target as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement,key=n.dataset.field;if(!key)return;edit(()=>{const o=object(),r=region(),l=level();if(key==='selectionX'||key==='selectionY'){if(!canEditSelection())return;const b=selectionBounds(project,l,selections);translateEntities(l,selections,key==='selectionX'?Number(n.value)-b.left:0,key==='selectionY'?Number(n.value)-b.top:0);}else if(o){if(key==='pivotX'||key==='pivotY'){o.pivot??={...project.assets.find(a=>a.id===o.assetId)!.pivot};o.pivot[key==='pivotX'?'x':'y']=Number(n.value);}else if(['x','y','scale','opacity'].includes(key))(o as any)[key]=Number(n.value);else if(['flipX','locked'].includes(key))(o as any)[key]=n.value==='true';else(o as any)[key]=n.value;}
  else if(r){if(key==='points')r.points=n.value.trim().split('\n').map(s=>{const[x,y]=s.split(',').map(Number);return {x,y};});else if(key==='enabled')r.enabled=n.value==='true';else if(key==='targetX'||key==='targetY'){if(n.value==='')r.target=null;else{const dest=project.levels.find(l=>l.id===r.targetLevelId);r.target??={...(dest?.spawn??{x:0,y:0})};r.target[key==='targetX'?'x':'y']=Number(n.value);}}else(r as any)[key]=n.value;}
  else {if(key==='levelName')l.name=n.value;else if(['width','height'].includes(key))(l as any)[key]=Number(n.value);else if(key==='spawnX'||key==='spawnY')l.spawn[key==='spawnX'?'x':'y']=Number(n.value);else if(key==='layerName')l.layers.find(l=>l.id===activeLayer)!.name=n.value;else if(key==='layerKind')l.layers.find(l=>l.id===activeLayer)!.kind=n.value as LayerKind;else(l as any)[key]=n.value;}});});
el('search').addEventListener('input',palette);el('project-name').addEventListener('change',()=>edit(()=>project.name=el<HTMLInputElement>('project-name').value));
el('save').addEventListener('click',()=>void save());el('export').addEventListener('click',()=>download(`${project.id}.project.json`,project));el('export-level').addEventListener('click',()=>download(`${level().id}.level.json`,exportEditorLevel(project,level())));
el('new-project').addEventListener('click',()=>{if(playing)return;localSave();project=newProject(project.assets);clearSelection();activeLayer=level().layers[2].id;undo.length=redo.length=0;fit();ui();localSave();void savedList();el('issues').innerHTML='<p class="hint">Bấm Kiểm tra để kiểm level mới.</p>';status('Dự án trống đã tạo. Bản nháp trước vẫn có trong Mở bản lưu.');});
async function openProject(p:EditorProject):Promise<void>{await loadAssets(p);localSave();project=p;clearSelection();undo.length=redo.length=0;playing=false;activate(p.activeLevelId);el('issues').innerHTML='<p class="hint">Bấm Kiểm tra để kiểm dự án vừa mở.</p>';status('Đã mở dự án.');}
el<HTMLSelectElement>('saved-projects').addEventListener('change',async()=>{const value=el<HTMLSelectElement>('saved-projects').value;if(!value)return;try{const raw=value.startsWith('draft:')?JSON.parse(localStorage.getItem(`game-solo-map-editor:${value.slice(6)}`)!):await(await fetch(`/api/map-editor/projects/${value}`)).json();await openProject(parseProject(raw));}catch(error){status(String(error));}});
el<HTMLInputElement>('import-project').addEventListener('change',async e=>{const n=e.target as HTMLInputElement,file=n.files?.[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('JSON vượt20 MB.');await openProject(parseProject(JSON.parse(await file.text())));}catch(error){status(String(error));}n.value='';});
el<HTMLInputElement>('import-level').addEventListener('change',async e=>{const n=e.target as HTMLInputElement,file=n.files?.[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('JSON vượt20 MB.');await openProject(mergeEditorLevel(project,JSON.parse(await file.text())));}catch(error){status(String(error));}n.value='';});
async function addAssets(assets:EditorAsset[]):Promise<void> {if(project.assets.length+assets.length>200)throw new Error('Thư viện tối đa 200 asset.');const next=structuredClone(project);next.assets.push(...assets);await loadAssets(next);edit(()=>{project.assets.push(...assets);chosenAsset=assets[0]?.id??chosenAsset;chosenPrefab='';if(assets[0]?.defaultLayer)activeLayer=level().layers.find(l=>l.kind===assets[0].defaultLayer)?.id??activeLayer;});setTool('place');ui();status(`Đã nhập ${assets.length} PNG. Chỉnh pivot và layer mặc định ở Thuộc tính asset.`);}
el<HTMLInputElement>('import-asset').addEventListener('change',async e=>{const n=e.target as HTMLInputElement;try{if(playing)return;await addAssets(await importPNGs(Array.from(n.files??[])));}catch(error){status(String(error));}n.value='';});
el<HTMLInputElement>('import-tileset').addEventListener('change',async e=>{const n=e.target as HTMLInputElement;try{if(!playing&&n.files?.[0])await addAssets(await sliceTileset(n.files[0],Number(el<HTMLInputElement>('tile-width').value),Number(el<HTMLInputElement>('tile-height').value),200-project.assets.length));}catch(error){status(String(error));}n.value='';});
window.addEventListener('keydown',e=>{if(!ready)return;const form=/INPUT|SELECT|TEXTAREA/.test((e.target as HTMLElement)?.tagName),key=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&key==='s'){e.preventDefault();void save();return;}if(form)return;
  if(key==='escape'){if(playing)testMode();else{draft=[];if(drag&&drag.mode!=='pan'&&drag.mode!=='marquee')project=drag.before;drag=null;setTool('select');ui();}return;}
  if(playing){if(key==='e'&&!e.repeat){traverse();return;}if(['w','a','s','d','arrowup','arrowleft','arrowdown','arrowright'].includes(key)){e.preventDefault();keys.add(key);}return;}
  if((e.ctrlKey||e.metaKey)&&key==='a'){e.preventDefault();selectAll();return;}if((e.ctrlKey||e.metaKey)&&key==='g'){e.preventDefault();groupSelection(e.shiftKey);return;}if((e.ctrlKey||e.metaKey)&&key==='c'){e.preventDefault();copySelection();return;}if((e.ctrlKey||e.metaKey)&&key==='v'){e.preventDefault();pasteSelection();return;}
  if(['arrowup','arrowdown','arrowleft','arrowright'].includes(key)&&selections.length){e.preventDefault();if(canEditSelection()){const step=Number(el<HTMLSelectElement>('snap').value)*(e.shiftKey?10:1);edit(()=>translateEntities(level(),selections,key==='arrowleft'?-step:key==='arrowright'?step:0,key==='arrowup'?-step:key==='arrowdown'?step:0));}return;}
  if(key==='f'){frameSelection();return;}if(key==='b'){setTool('brush');return;}
  if((e.ctrlKey||e.metaKey)&&key==='z'){e.preventDefault();history(!e.shiftKey);}else if((e.ctrlKey||e.metaKey)&&key==='d'){e.preventDefault();duplicate();}else if(key==='delete'||key==='backspace'){e.preventDefault();remove();}else if(key==='enter'&&draft.length)finish();else if(key==='v')setTool('select');else if(key==='h')setTool('pan');else if(key===' '){e.preventDefault();space=true;}
});
window.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key===' ')space=false;});window.addEventListener('blur',()=>{keys.clear();space=false;});window.addEventListener('pagehide',()=>{if(project)localSave();});
function shape(points:Array<{x:number;y:number}>,fill:string,stroke:string):void {if(!points.length)return;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=1/view.zoom;ctx.stroke();}
function render(now:number):void {
  const dt=Math.min(.25,(now-last)/1000);last=now;requestAnimationFrame(render);if(!ready)return;
  const l=level();if(now-lastMinimap>180){drawMinimap();lastMinimap=now;}if(playing){const next=moveInEditor(l,player,{x:Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),y:Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'))},dt);const distance=Math.hypot(next.x-player.x,next.y-player.y);player=next;animation.updateFromTravel(distance,player.direction,player.moving,24);view.x=viewport.clientWidth/2-player.x*view.zoom;view.y=viewport.clientHeight/2-player.y*view.zoom;}
  const dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(viewport.clientWidth*dpr)||canvas.height!==Math.round(viewport.clientHeight*dpr)){canvas.width=Math.round(viewport.clientWidth*dpr);canvas.height=Math.round(viewport.clientHeight*dpr);}
  ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,canvas.width/dpr,canvas.height/dpr);ctx.translate(view.x,view.y);ctx.scale(view.zoom,view.zoom);ctx.fillStyle=l.background;ctx.fillRect(0,0,l.width,l.height);ctx.save();ctx.beginPath();ctx.rect(0,0,l.width,l.height);ctx.clip();
  const objectOrder=new Map(l.objects.map((o,i)=>[o.id,i]));const rows:Array<{o:EditorObject;a:EditorAsset;part:EditorAsset['parts'][number];band:number;order:number;cover:boolean}>=[];
  for(const o of l.objects){const a=project.assets.find(a=>a.id===o.assetId);if(!a)continue;const box=bounds(o,a);if((box.left+box.w)*view.zoom+view.x<0||box.left*view.zoom+view.x>viewport.clientWidth||(box.top+box.h)*view.zoom+view.y<0||box.top*view.zoom+view.y>viewport.clientHeight)continue;for(const part of a.parts){const layer=l.layers.find(x=>x.id===(part.cover?o.coverLayerId:o.layerId));const base=l.layers.find(x=>x.id===o.layerId);if(!layer||(!playing&&(!layer.visible||(el<HTMLInputElement>('solo-layer').checked&&layer.id!==activeLayer)))||(playing&&(!layer.enabled||!base?.enabled)))continue;rows.push({o,a,part,band:layer.kind==='ground'?0:layer.kind==='decor'?1:2,order:l.layers.indexOf(layer),cover:part.cover||layer.kind==='cover'});}}
  rows.sort((a,b)=>a.band-b.band||(a.band===2?a.o.y-b.o.y||Number(a.cover)-Number(b.cover):a.order-b.order)||objectOrder.get(a.o.id)!-objectOrder.get(b.o.id)!);
  const frame=playing?atlas.frames[animation.frameId]:null;
  if(frame&&!actorFrameMasks.has(animation.frameId))actorFrameMasks.set(animation.frameId,cropAlpha(actorSourceMask,frame));
  const actorMask=frame?actorFrameMasks.get(animation.frameId)!:null;
  const drawActor=()=>{if(!frame)return;ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(actorImage,frame.x,frame.y,frame.w,frame.h,player.x-32,player.y-88,64,96);ctx.restore();};
  let actorDrawn=false;
  for(const row of rows){if(playing&&!actorDrawn&&row.band===2&&row.o.y>player.y){drawActor();actorDrawn=true;}const {o,a,part}=row,img=images.get(part.file);if(!img)continue;const b=bounds(o,a),layer=l.layers[row.order];ctx.save();ctx.imageSmoothingEnabled=false;ctx.globalAlpha=o.opacity*(layer.enabled?1:.3);
    if(playing&&row.cover&&player.y<o.y&&actorMask&&opaqueMasksOverlap({mask:img.mask,left:b.left,top:b.top,scaleX:o.scale,scaleY:o.scale,flipX:o.flipX},{mask:actorMask,left:player.x-32,top:player.y-88}))ctx.globalAlpha*=.35;
    if(o.flipX){ctx.translate(b.left+b.w,b.top);ctx.scale(-1,1);ctx.drawImage(img.image,0,0,b.w,b.h);}else ctx.drawImage(img.image,b.left,b.top,b.w,b.h);ctx.restore();}
  if(playing&&!actorDrawn)drawActor();ctx.restore();
  if(!playing&&el<HTMLInputElement>('grid').checked){const step=Math.max(16,Number(el<HTMLSelectElement>('snap').value)),left=Math.max(0,Math.floor((-view.x/view.zoom)/step)*step),top=Math.max(0,Math.floor((-view.y/view.zoom)/step)*step),right=Math.min(l.width,(-view.x+viewport.clientWidth)/view.zoom),bottom=Math.min(l.height,(-view.y+viewport.clientHeight)/view.zoom);ctx.strokeStyle='#21382b25';ctx.lineWidth=1/view.zoom;ctx.beginPath();for(let x=left;x<=right;x+=step){ctx.moveTo(x,Math.max(0,top));ctx.lineTo(x,bottom);}for(let y=top;y<=bottom;y+=step){ctx.moveTo(left,y);ctx.lineTo(right,y);}ctx.stroke();}
  if(el<HTMLInputElement>('show-regions').checked)for(const r of l.regions){if(!l.layers.find(x=>x.id===r.layerId)?.visible)continue;const color=r.kind==='walk'?'#54b57d':r.kind==='block'?'#e76c60':'#ab87ef';shape(r.points,color+'35',color);if(selected?.id===r.id&&!playing)for(const p of r.points){ctx.beginPath();ctx.arc(p.x,p.y,5/view.zoom,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.stroke();}}
  if(!playing){ctx.strokeStyle='#d4e5ae';ctx.lineWidth=2/view.zoom;for(const s of selections){const b=entityBounds(project,l,s);ctx.strokeRect(b.left,b.top,b.w,b.h);}const o=object();if(o){ctx.beginPath();ctx.moveTo(o.x-8/view.zoom,o.y);ctx.lineTo(o.x+8/view.zoom,o.y);ctx.moveTo(o.x,o.y-8/view.zoom);ctx.lineTo(o.x,o.y+8/view.zoom);ctx.stroke();}
    const ghost=project.assets.find(a=>a.id===chosenAsset);if(ghost&&['place','brush','paint-rect'].includes(tool)){const p=tool==='place'?snapped(hover):gridStroke(hover,hover,brushStep())[0];const b=bounds({x:p.x,y:p.y,scale:1,flipX:false} as EditorObject,ghost);ctx.save();ctx.globalAlpha=.45;ctx.imageSmoothingEnabled=false;for(const part of ghost.parts){const img=images.get(part.file);if(img)ctx.drawImage(img.image,b.left,b.top,b.w,b.h);}ctx.restore();}
    ctx.beginPath();ctx.arc(l.spawn.x,l.spawn.y,8,0,Math.PI*2);ctx.strokeStyle='#324eac';ctx.stroke();ctx.fillStyle='#233974';ctx.font=`${11/view.zoom}px Segoe UI`;ctx.fillText('Spawn',l.spawn.x+12,l.spawn.y);
    if(draft.length)shape([...draft,snapped(hover)],'#e6e2ac35','#e8e9b1');if(drag?.mode==='rect'||drag?.mode==='marquee'){const a=drag.start,b=snapped(hover);shape([a,{x:b.x,y:a.y},b,{x:a.x,y:b.y}],'#e6e2ac35','#e8e9b1');}}
}
async function init():Promise<void>{
  const kit=await(await fetch('/assets/map-kit/manifest.json',{cache:'no-store'})).json();const assets:EditorAsset[]=kit.assets.map((a:any)=>({id:a.id,name:a.label,width:a.width,height:a.height,pivot:{x:a.suggestedPivot[0],y:a.suggestedPivot[1]},parts:a.layers.map((p:any)=>({id:p.id,file:`/assets/map-kit/${p.file}`,cover:p.role==='optional_occluder'}))}));
  for(const a of assets)for(const part of a.parts)libraryFiles.add(part.file);
  const revision=String(kit.libraryRevision??kit.version),revisionKey='game-solo-map-editor-library-revision';let libraryReset=localStorage.getItem(revisionKey)!==revision;
  const lastId=localStorage.getItem('game-solo-map-editor-last');try{project=!libraryReset&&lastId?parseProject(JSON.parse(localStorage.getItem(`game-solo-map-editor:${lastId}`)!)):newProject(assets);}catch{project=newProject(assets);libraryReset=true;}
  if(project.assets.some(a=>a.parts.some(p=>p.file.startsWith('/assets/map-kit/')&&!libraryFiles.has(p.file)))){project=newProject(assets);libraryReset=true;}
  activeLayer=level().layers.find(l=>l.kind==='depth')?.id??level().layers[0].id;
  const catalog=await(await fetch('/assets/catalog.json',{cache:'no-store'})).json(),actor=catalog.actors.find((a:any)=>a.id==='AVATAR-NOVICE-MALE');atlas=normalizeAtlas(await(await fetch(actor.metadataUrl)).json());animation=new AnimationPlayer(atlas);actorImage=new Image();actorImage.src=actor.atlasUrl;
  await Promise.all([loadAssets(),actorImage.decode()]);actorSourceMask=imageAlpha(actorImage);ready=true;document.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement|HTMLTextAreaElement>('input,button,select,textarea').forEach(n=>n.disabled=false);fit();ui();
  if(libraryReset){localSave();localStorage.setItem(revisionKey,revision);}
  await savedList();status(libraryReset?'Đã mở dự án trống với thư viện mới. Bản nháp trước vẫn có trong Mở bản lưu.':'Sẵn sàng. Nhập PNG hoặc kéo asset để biên tập map.');
}
function selectAll():void {if(playing)return;setSelection(selectionCandidates().flatMap(s=>groupMembers(level(),s)));ui();}
function groupSelection(ungroup=false):void {if(!selections.length||!canEditSelection())return;edit(()=>{const id=uid();for(const s of selections){const item=entity(level(),s)!;if(ungroup)delete item.groupId;else item.groupId=id;}});status(ungroup?'Đã tách nhóm.':'Đã nhóm vật và vùng. Alt+bấm để chỉnh riêng một thành phần.');}
function frameSelection():void {if(playing)return;if(!selections.length){fit();return;}const b=selectionBounds(project,level(),selections);view.zoom=Math.max(.25,Math.min(2,(viewport.clientWidth-80)/Math.max(1,b.w),(viewport.clientHeight-80)/Math.max(1,b.h)));view.x=viewport.clientWidth/2-(b.left+b.w/2)*view.zoom;view.y=viewport.clientHeight/2-(b.top+b.h/2)*view.zoom;el<HTMLInputElement>('zoom').value=String(Math.round(view.zoom*100)/100);}
function copySelection():void {if(!selections.length)return;clipboard=capturePrefab(project,level(),selections,'Bản sao chọn');status('Đã sao chép. Ctrl+V đặt cụm tại tâm khung nhìn.');}
function pasteSelection():void {const copied=clipboard;if(!copied)return;edit(()=>setSelection(instantiatePrefab(project,level(),copied,snapped({x:(viewport.clientWidth/2-view.x)/view.zoom,y:(viewport.clientHeight/2-view.y)/view.zoom}))));}
function engineUi():void {
  const a=project.assets.find(a=>a.id===chosenAsset),categories=[['terrain','Nền / tile'],['building','Công trình'],['nature','Thiên nhiên'],['prop','Đạo cụ'],['other','Khác']],kinds=[['ground','Nền'],['decor','Trang trí thấp'],['depth','Theo chân'],['cover','Tán / mái']];
  const field=(key:string,label:string,value:unknown,type='text')=>`<label class="form-row">${label}<input data-asset-prop="${key}" type="${type}" value="${esc(value)}" /></label>`;
  const select=(key:string,label:string,value:string,options:string[][])=>`<label class="form-row">${label}<select data-asset-prop="${key}">${options.map(([id,name])=>`<option value="${id}" ${id===value?'selected':''}>${name}</option>`).join('')}</select></label>`;
  el('asset-settings').innerHTML=a?`<p>${a.width} × ${a.height} · ${a.parts.length} part</p>`+field('name','Tên asset',a.name)+select('category','Phân loại',a.category??'other',categories)+select('defaultLayer','Layer khi chọn asset',a.defaultLayer??'depth',kinds)+`<div class="form-pair">${field('pivotX','Pivot X',a.pivot.x,'number')}${field('pivotY','Pivot Y',a.pivot.y,'number')}</div><p class="hint">Pivot thư viện dùng cho instance chưa ghi đè. Part mới phải cùng cỡ canvas.</p>`+a.parts.map((part,i)=>`<div class="part-row"><label><input type="checkbox" data-part-cover="${part.id}" ${part.cover?'checked':''} /> Part ${i+1} · phần che</label><div class="library-actions"><button data-replace-part="${part.id}">Thay PNG</button><button data-remove-part="${part.id}" ${a.parts.length===1?'disabled':''}>Xóa part</button></div></div>`).join(''):'<p class="hint">Chọn asset trong thư viện để chỉnh tên, phân loại, pivot và part.</p>';
  el('prefabs').innerHTML=(project.prefabs??[]).map(f=>`<div class="prefab-row"><button data-place-prefab="${f.id}">${esc(f.name)} · ${f.objects.length} vật / ${f.regions.length} vùng</button><button data-remove-prefab="${f.id}" title="Xóa mẫu prefab">×</button></div>`).join('')||'<p class="hint">Chọn các vật/vùng rồi Lưu chọn. Prefab được lưu trong dự án và thư viện xuất.</p>';
  for(const id of ['select-all','group','ungroup','align','save-prefab','import-library','import-tileset','asset-category','import-asset','brush-step','tile-width','tile-height','prefab-name'])el<HTMLInputElement|HTMLButtonElement>(id).disabled=playing;
  for(const id of ['import-part','remove-asset'])el<HTMLInputElement|HTMLButtonElement>(id).disabled=playing||!a;
  el('asset-settings').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('input,select,button').forEach(n=>{if(playing)n.disabled=true;});el('prefabs').querySelectorAll<HTMLButtonElement>('button').forEach(n=>n.disabled=playing);
}
el('select-all').addEventListener('click',selectAll);el('frame-selection').addEventListener('click',frameSelection);el('group').addEventListener('click',()=>groupSelection());el('ungroup').addEventListener('click',()=>groupSelection(true));
el('align').addEventListener('click',()=>{if(canEditSelection())edit(()=>alignEntities(project,level(),selections,el<HTMLSelectElement>('alignment').value as Alignment));});
el('save-prefab').addEventListener('click',()=>{if(!selections.length){status('Chọn các vật/vùng cần lưu thành prefab.');return;}edit(()=>{project.prefabs??=[];project.prefabs.push(capturePrefab(project,level(),selections,el<HTMLInputElement>('prefab-name').value.trim().slice(0,120)||'Cụm mới'));});});
el('prefabs').addEventListener('click',e=>{const place=(e.target as HTMLElement).closest<HTMLElement>('[data-place-prefab]'),remove=(e.target as HTMLElement).closest<HTMLElement>('[data-remove-prefab]');if(place){chosenPrefab=place.dataset.placePrefab!;chosenAsset='';setTool('prefab');ui();status('Bấm vào map để đặt prefab; giữ hình và các vùng cùng vị trí.');}else if(remove)edit(()=>project.prefabs=project.prefabs?.filter(f=>f.id!==remove.dataset.removePrefab));});
el('asset-category').addEventListener('change',palette);
el('asset-settings').addEventListener('change',e=>{const n=e.target as HTMLInputElement,key=n.dataset.assetProp,a=project.assets.find(a=>a.id===chosenAsset);if(!a)return;edit(()=>{if(n.dataset.partCover){a.parts.find(p=>p.id===n.dataset.partCover)!.cover=n.checked;}else if(key==='pivotX'||key==='pivotY')a.pivot[key==='pivotX'?'x':'y']=Number(n.value);else if(key)(a as any)[key]=n.value;});});
el<HTMLInputElement>('import-part').addEventListener('change',async e=>{const n=e.target as HTMLInputElement,a=project.assets.find(a=>a.id===chosenAsset);try{if(!playing&&a&&n.files?.[0]){const {url,image:img}=await readPNG(n.files[0]);if(img.width!==a.width||img.height!==a.height)throw new Error('Part phải cùng kích thước canvas với asset.');if(a.parts.length>=8)throw new Error('Asset tối đa 8 part.');const next=structuredClone(project),part={id:uid(),file:url,cover:true};next.assets.find(v=>v.id===a.id)!.parts.push(part);await loadAssets(next);edit(()=>project.assets.find(v=>v.id===a.id)!.parts.push(part));status('Đã thêm part che. Các part dùng chung canvas/pivot.');}}catch(error){status(String(error));}n.value='';});
el('asset-settings').addEventListener('click',e=>{if(playing)return;const a=project.assets.find(a=>a.id===chosenAsset),replace=(e.target as HTMLElement).closest<HTMLElement>('[data-replace-part]'),remove=(e.target as HTMLElement).closest<HTMLElement>('[data-remove-part]');if(!a)return;if(replace){replacingPart={assetId:a.id,partId:replace.dataset.replacePart!};el<HTMLInputElement>('replace-part').click();}else if(remove&&a.parts.length>1){edit(()=>a.parts=a.parts.filter(p=>p.id!==remove.dataset.removePart));void loadAssets().then(palette);}});
el<HTMLInputElement>('replace-part').addEventListener('change',async e=>{const n=e.target as HTMLInputElement,pending=replacingPart;replacingPart=null;try{const a=project.assets.find(a=>a.id===pending?.assetId);if(!playing&&pending&&a&&n.files?.[0]){const {url,image:img}=await readPNG(n.files[0]);if(img.width!==a.width||img.height!==a.height)throw new Error('PNG thay thế phải giữ kích thước canvas; vị trí instance và pivot được giữ.');const next=structuredClone(project);next.assets.find(a=>a.id===pending.assetId)!.parts.find(p=>p.id===pending.partId)!.file=url;await loadAssets(next);edit(()=>project.assets.find(a=>a.id===pending.assetId)!.parts.find(p=>p.id===pending.partId)!.file=url);status('Đã thay PNG của part; các vị trí và vùng hoạt động được giữ.');}}catch(error){status(String(error));}n.value='';});
el('remove-asset').addEventListener('click',()=>{const id=chosenAsset;if(project.levels.some(l=>l.objects.some(o=>o.assetId===id))||project.prefabs?.some(f=>f.objects.some(o=>o.assetId===id))){status('Asset đang được dùng trong level/prefab. Xóa hoặc thay instance trước.');return;}edit(()=>{project.assets=project.assets.filter(a=>a.id!==id);chosenAsset='';});});
el('export-library').addEventListener('click',()=>download(`${project.id}.assets.json`,exportAssetLibrary(project)));
el<HTMLInputElement>('import-library').addEventListener('change',async e=>{const n=e.target as HTMLInputElement;try{if(!playing&&n.files?.[0]){if(n.files[0].size>20*1024*1024)throw new Error('Thư viện vượt 20 MB.');const next=mergeAssetLibrary(project,JSON.parse(await n.files[0].text()));await loadAssets(next);edit(()=>project=next);status('Đã nhập thư viện và prefab; các level hiện tại được giữ.');}}catch(error){status(String(error));}n.value='';});
function validate():ReturnType<typeof auditProject> {const issues=auditProject(project);el('issues').innerHTML=issues.length?issues.map(i=>`<button class="issue ${i.severity}" data-issue-level="${i.levelId}" ${i.entity?`data-issue-id="${i.entity.id}" data-issue-kind="${i.entity.kind}"`:''}>${esc(project.levels.find(l=>l.id===i.levelId)?.name)} · ${esc(i.message)}</button>`).join(''):'<p class="hint">Không có lỗi Spawn, vùng hoặc cửa nối. ART/bố cục vẫn cần bạn đánh giá.</p>';status(`Kiểm level: ${issues.filter(i=>i.severity==='error').length} lỗi, ${issues.filter(i=>i.severity==='warning').length} lưu ý.`);return issues;}
el('validate').addEventListener('click',validate);el('export-runtime').addEventListener('click',()=>{try{validate();download(`${project.id}.runtime.json`,exportRuntimeProject(project));status('Đã xuất runtime: hình, vùng hoạt động và luồng level.');}catch(error){status(String(error));}});
el('issues').addEventListener('click',e=>{if(playing)return;const b=(e.target as HTMLElement).closest<HTMLElement>('[data-issue-level]');if(!b)return;if(!project.levels.some(l=>l.id===b.dataset.issueLevel)){el('issues').innerHTML='<p class="hint">Dữ liệu đã đổi. Bấm Kiểm tra để cập nhật.</p>';return;}activate(b.dataset.issueLevel!);if(b.dataset.issueId){choose({kind:b.dataset.issueKind as 'object'|'region',id:b.dataset.issueId});ui();frameSelection();}else{zoomTo(1);view.x=viewport.clientWidth/2-level().spawn.x;view.y=viewport.clientHeight/2-level().spawn.y;}});
function minimapTransform(){const c=el<HTMLCanvasElement>('minimap'),l=level(),scale=Math.min(c.width/l.width,c.height/l.height);return {c,l,scale,x:(c.width-l.width*scale)/2,y:(c.height-l.height*scale)/2};}
function drawMinimap():void {const {c,l,scale,x,y}=minimapTransform(),m=c.getContext('2d')!;m.setTransform(1,0,0,1,0,0);m.clearRect(0,0,c.width,c.height);m.translate(x,y);m.scale(scale,scale);m.fillStyle=l.background;m.fillRect(0,0,l.width,l.height);for(const o of l.objects){const layer=l.layers.find(l=>l.id===o.layerId);if(!layer||(playing?!layer.enabled:!layer.visible))continue;const a=project.assets.find(a=>a.id===o.assetId)!,b=bounds(o,a);m.fillStyle=a.category==='terrain'?'#9baa72':'#54735b';m.fillRect(b.left,b.top,b.w,b.h);}for(const r of l.regions){m.beginPath();r.points.forEach((p,i)=>i?m.lineTo(p.x,p.y):m.moveTo(p.x,p.y));m.closePath();m.fillStyle=r.kind==='block'?'#b65c5088':r.kind==='portal'?'#8b5ee7aa':'#6eb58744';m.fill();}m.strokeStyle='#fff';m.lineWidth=1/scale;m.strokeRect(-view.x/view.zoom,-view.y/view.zoom,viewport.clientWidth/view.zoom,viewport.clientHeight/view.zoom);m.fillStyle='#3266c4';m.beginPath();m.arc(playing?player.x:l.spawn.x,playing?player.y:l.spawn.y,3/scale,0,Math.PI*2);m.fill();}
el('minimap').addEventListener('pointerdown',e=>{if(playing)return;const {c,scale,x,y}=minimapTransform(),b=c.getBoundingClientRect(),wx=((e.clientX-b.left)*c.width/b.width-x)/scale,wy=((e.clientY-b.top)*c.height/b.height-y)/scale;view.x=viewport.clientWidth/2-wx*view.zoom;view.y=viewport.clientHeight/2-wy*view.zoom;});
Object.assign(window,{__mapEditorDiagnostics:()=>({ready,project:structuredClone(project),selected,selections:structuredClone(selections),chosenAsset,chosenPrefab,activeLayer,tool,playing,player:{...player},view:{...view},undoCount:undo.length,redoCount:redo.length,validPlayer:ready&&playing?editorWalkable(level(),player):null})});
requestAnimationFrame(render);init().catch(error=>status(`Không nạp được editor: ${String(error)}. Chạy npm run assets rồi tải lại.`));
