import {setupAssetCut} from './map-editor-cut';
import {cutPlacement} from '../../shared/asset-extraction';
import {sampleSpline,nearestSplineEdge,updateSplineRegion,MAX_SPLINE_ANCHORS} from '../../shared/region-spline';
import { newProject,newLevel,parseProject,uid,inside,regionActivity,regionsOnDisabledLayers,enableRegionLayers,editorWalkable,moveInEditor,portalAt,exportEditorLevel,mergeEditorLevel,type EditorProject,type EditorAsset,type EditorLevel,type EditorObject,type EditorRegion,type LayerKind } from '../../shared/map-editor';
import { AnimationPlayer,normalizeAtlas,type Atlas } from './atlas';
import { imageAlpha,cropAlpha,opaqueMasksOverlap,type AlphaMask } from './occlusion';
import {readAssetImage,importImages,sliceTileset} from './map-editor-import';
import type { Motion } from '../../shared/world';
import { setupStudio } from './map-editor-studio';
import { alignWithGuides, type AlignmentGuide } from '../../shared/editor-guides';
import {entity,entityKey,entityBounds,objectBounds,selectionBounds,groupMembers,translateEntities,duplicateEntities,duplicateAsset,alignEntities,capturePrefab,instantiatePrefab,gridStroke,exportAssetLibrary,mergeAssetLibrary,auditProject,exportRuntimeProject,type EntitySelection,type Alignment} from '../../shared/level-design';

const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const canvas=el<HTMLCanvasElement>('map-canvas'),viewport=el('viewport'),ctx=canvas.getContext('2d')!;
document.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement|HTMLTextAreaElement>('input,button,select,textarea').forEach(n=>n.disabled=true);
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Selection={kind:'object'|'region';id:string}|null;
let project:EditorProject,selected:Selection=null,activeLayer='',chosenAsset='',tool='select',ready=false,playing=false,player:Motion={x:0,y:0,direction:'south',moving:false};
let selections:EntitySelection[]=[],chosenPrefab='',clipboard:ReturnType<typeof capturePrefab>|null=null;
let lastMinimap=0;
let editDomain:'scene'|'navigation'='scene';
let inspectorContext:'level'|'layer'|'asset'|'selection'='level';
let alignmentGuides:AlignmentGuide[]=[];
let savedProjectJSON='';
const collapsedLayers=new Set<string>();
const inspectorFoldouts=new Map<string,boolean>();
const layerIcons=[`<svg viewBox="0 0 16 16"><path d="M1 8c3-6 11-6 14 0-3 6-11 6-14 0Z"/><circle cx="8" cy="8" r="2"/></svg>`,`<svg viewBox="0 0 16 16"><rect x="3" y="7" width="10" height="7" rx="1"/><path d="M5 7V5a3 3 0 0 1 6 0v2"/></svg>`,`<svg viewBox="0 0 16 16"><path d="m3 8 3 3 7-7"/></svg>`];
let replacingPart:{assetId:string;partId:string}|null=null;
let view={x:0,y:0,zoom:1},draft:Array<{x:number;y:number}>=[],hover={x:0,y:0},space=false,last=performance.now();
let drag:{mode:'pan'|'selection'|'marquee'|'brush'|'erase'|'vertex'|'rect';start:{x:number;y:number};screen:{x:number;y:number};before:EditorProject;index?:number;origin?:any;additive?:boolean;seen?:Set<string>;lastPoint?:{x:number;y:number}}|null=null;
let savedTimer:ReturnType<typeof setTimeout>|undefined;
let saveQueue:Promise<void>=Promise.resolve();
let editView:{levelId:string;view:{x:number;y:number;zoom:number}}|null=null;
const undo:EditorProject[]=[],redo:EditorProject[]=[],keys=new Set<string>();
const images=new Map<string,{image:HTMLImageElement;mask:AlphaMask}>();
const thumbnails=new Map<string,string>();
const libraryFiles=new Set<string>();
let actorImage:HTMLImageElement,actorSourceMask:AlphaMask,atlas:Atlas,animation:AnimationPlayer;
const actorFrameMasks=new Map<string,AlphaMask>();
const level=():EditorLevel=>project.levels.find(l=>l.id===project.activeLevelId)!;
const layerName=(id:string)=>level().layers.find(l=>l.id===id)?.name??'';
const object=()=>selected?.kind==='object'?level().objects.find(o=>o.id===selected!.id):undefined;
const region=()=>selected?.kind==='region'?level().regions.find(r=>r.id===selected!.id):undefined;
function setSelection(items:EntitySelection[]):void {selections=[...new Map(items.filter(s=>entity(level(),s)).map(s=>[entityKey(s),s])).values()];selected=selections.at(-1)??null;if(selected)inspectorContext='selection';}
function clearSelection():void {selections=[];selected=null;inspectorContext='level';}
function choose(s:Selection,additive=false,individual=false):void {if(!s){if(!additive)clearSelection();return;}const members=individual?[s]:groupMembers(level(),s),keys=new Set(members.map(entityKey));setSelection(additive?(members.every(m=>selections.some(v=>entityKey(v)===entityKey(m)))?selections.filter(v=>!keys.has(entityKey(v))):[...selections,...members.filter(v=>entityKey(v)!==entityKey(s)),s]):[...members.filter(v=>entityKey(v)!==entityKey(s)),s]);}
const objectLayerLocked=(o:EditorObject)=>Boolean(level().layers.find(l=>l.id===o.layerId)?.locked||(project.assets.find(a=>a.id===o.assetId)?.parts.some(p=>p.cover)&&level().layers.find(l=>l.id===o.coverLayerId)?.locked));
const status=(s:string)=>{el('status').textContent=s;};
const snap=(n:number)=>Math.round(n/Number(el<HTMLSelectElement>('snap').value))*Number(el<HTMLSelectElement>('snap').value);
const world=(e:{clientX:number;clientY:number})=>{const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left-view.x)/view.zoom,y:(e.clientY-b.top-view.y)/view.zoom};};
const snapped=(p:{x:number;y:number})=>({x:snap(p.x),y:snap(p.y)});
const image=async(file:string)=>{if(images.has(file))return;const img=new Image();img.src=file;await img.decode();images.set(file,{image:img,mask:imageAlpha(img)});};
async function loadAssets(p=project):Promise<void>{for(const a of p.assets)for(const part of a.parts){if(part.file.startsWith('/assets/map-kit/')&&!libraryFiles.has(part.file))throw new Error(`Asset cũ đã xóa khỏi thư viện: ${a.name}. Bản lưu vẫn được giữ; cần PNG mới để mở lại.`);}await Promise.all(p.assets.flatMap(a=>a.parts.map(p=>image(p.file))));for(const a of p.assets){for(const part of a.parts){const i=images.get(part.file)!.image;if(i.width!==a.width||i.height!==a.height)throw new Error(`Cỡ PNG không khớp: ${a.name}`);}if(a.parts.length>1){const c=document.createElement('canvas');c.width=a.width;c.height=a.height;for(const part of a.parts)c.getContext('2d')!.drawImage(images.get(part.file)!.image,0,0);thumbnails.set(a.id,c.toDataURL());}}}
function localSave():void {
  try{localStorage.setItem(`game-solo-map-editor:${project.id}`,JSON.stringify(project));localStorage.setItem('game-solo-map-editor-last',project.id);}
  catch{studio.saveState('Chưa lưu được bản nháp','error');status('Bản nháp vượt bộ nhớ trình duyệt. Bấm Lưu dự án hoặc Xuất JSON để giữ dữ liệu.');}
}
function changed(before:EditorProject):boolean {
  try{project=parseProject(project);}catch(error){project=before;status(String(error));ui();return false;}
  if(JSON.stringify(before)===JSON.stringify(project)){ui();return true;}
  el('issues').innerHTML='<p class="hint">Dữ liệu đã đổi. Bấm Kiểm tra để cập nhật kết quả.</p>';undo.push(before);if(undo.length>40)undo.shift();redo.length=0;
  studio.saveState('Có thay đổi · chưa lưu file','dirty');clearTimeout(savedTimer);savedTimer=setTimeout(localSave,350);ui();status('Bản nháp đã sửa · Ctrl+S để lưu vào dự án.');return true;
}
function edit(fn:()=>void):boolean {if(playing){status('Dừng Test để chỉnh map.');return false;}const before=structuredClone(project);try{fn();return changed(before);}catch(error){project=before;clearSelection();ui();status(String(error));return false;}}
function updateCoordinates():void {el('coordinates').textContent=`${Math.round(hover.x)}, ${Math.round(hover.y)} · ${view.zoom.toFixed(2)}×`;}
function fit():void {const l=level();view.zoom=Math.min(1,(viewport.clientWidth-60)/l.width,(viewport.clientHeight-60)/l.height);view.zoom=Math.max(.05,view.zoom);view.x=(viewport.clientWidth-l.width*view.zoom)/2;view.y=(viewport.clientHeight-l.height*view.zoom)/2;el<HTMLInputElement>('zoom').value=String(Math.round(view.zoom*100)/100);updateCoordinates();}
function zoomTo(z:number,p={x:viewport.clientWidth/2,y:viewport.clientHeight/2}):void {const wx=(p.x-view.x)/view.zoom,wy=(p.y-view.y)/view.zoom;view.zoom=Math.max(.05,Math.min(4,z));view.x=p.x-wx*view.zoom;view.y=p.y-wy*view.zoom;el<HTMLInputElement>('zoom').value=String(Math.round(view.zoom*100)/100);updateCoordinates();}
function setDomain(value:'scene'|'navigation'):void {
  if(playing||value===editDomain)return;
  editDomain=value;clearSelection();draft=[];tool='select';alignmentGuides=[];
  const kind=value==='navigation'?'regions':'depth';activeLayer=level().layers.find(l=>l.kind===kind)?.id??activeLayer;
  ui();status(value==='navigation'?'Vẽ Đi / Chặn / Cửa trên nền. V để chọn và sửa đỉnh.':'Chọn và bố trí hình. Vùng không bắt thao tác trong chế độ này.');
}
function setTool(value:string):void {
  if(playing)return;
  const domain=value.startsWith('walk')||value.startsWith('block')||value.startsWith('portal')||value==='spawn'?'navigation':['place','brush','paint-rect','erase','prefab'].includes(value)?'scene':editDomain;
  if(domain!==editDomain)setDomain(domain);
  tool=value;draft=[];alignmentGuides=[];refreshStudio();
  status(tool==='place'?'Bấm vào map để đặt hình; Esc trở lại chọn.':(tool.endsWith('poly')||tool.endsWith('spline'))?'Bấm các đỉnh; bấm đỉnh đầu hoặc Enter để đóng; Backspace bỏ đỉnh cuối.':'Kéo để chỉnh; Space hoặc chuột giữa để di chuyển khung.');
}
function activate(id:string):void {project.activeLevelId=id;clearSelection();activeLayer=level().layers.find(l=>l.kind===(editDomain==='navigation'?'regions':'depth'))?.id??level().layers[0].id;draft=[];keys.clear();if(playing){player={...level().spawn,direction:'south',moving:false};}fit();ui();localSave();}
function download(name:string,value:unknown):void {const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function savedList():Promise<void>{
  const select=el<HTMLSelectElement>('saved-projects');select.replaceChildren(new Option('Mở bản lưu…',''));
  try{const r=await fetch('/api/map-editor/projects');if(r.ok){for(const p of (await r.json()).projects)select.add(new Option(`${p.name} · dự án`,p.id));}}catch{/* Browser drafts still work without the local API. */}
  for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)!;if(!key.startsWith('game-solo-map-editor:'))continue;try{const p=parseProject(JSON.parse(localStorage.getItem(key)!));select.add(new Option(`${p.name} · nháp trình duyệt`,`draft:${p.id}`));}catch{/* Preserve invalid old drafts. */}}
}
function save():Promise<void>{localSave();const snapshot=structuredClone(project);studio.saveState('Đang lưu file…','saving');status('Đang chờ lưu vào dự án…');const work=async()=>{try{const r=await fetch(`/api/map-editor/projects/${snapshot.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});const result=await r.json();if(!r.ok)throw new Error(result.error);if(project.id===snapshot.id){savedProjectJSON=JSON.stringify(snapshot);const clean=JSON.stringify(project)===savedProjectJSON;studio.saveState(clean?'Đã lưu vào dự án':'Có thay đổi mới · chưa lưu file',clean?'saved':'dirty');status(clean?`Đã lưu: ${result.path}`:'Đã lưu phiên bản vừa gửi; còn thay đổi mới chưa lưu.');}await savedList();}catch(error){if(project.id===snapshot.id)studio.saveState('Lưu file thất bại · hãy xuất JSON','error');status(`Chưa lưu được file dự án: ${String(error)}. Xuất JSON để lưu bản này.`);}};saveQueue=saveQueue.then(work,work);return saveQueue;}
function palette():void {
  const search=el<HTMLInputElement>('search').value.toLocaleLowerCase('vi'),category=el<HTMLSelectElement>('asset-category').value;
  el('palette').innerHTML=project.assets.filter(a=>a.name.toLocaleLowerCase('vi').includes(search)&&(!category||(a.category??'other')===category)).map(a=>`<button class="asset-card ${a.id===chosenAsset?'selected':''}" draggable="${!playing}" ${playing?'disabled':''} data-asset="${esc(a.id)}" title="${a.width} × ${a.height} · kéo vào map"><img draggable="false" loading="lazy" src="${esc(thumbnails.get(a.id)??a.parts[0].file)}" alt="" /><span>${esc(a.name)}</span><small>${a.width} × ${a.height} px</small></button>`).join('')||(project.assets.length?'<p class="hint">Không có hình khớp từ khóa / phân loại.</p>':'<div class="library-empty"><strong>Thư viện trống</strong><p>Nhập hình nền, cây, nhà hoặc tileset để bắt đầu.</p></div>');
}
const inputField=(name:string,label:string,value:unknown,type='text',extra='')=>`<label class="form-row">${label}<input data-field="${name}" type="${type}" value="${esc(value)}" ${extra} /></label>`;
const selectField=(name:string,label:string,value:string,options:Array<[string,string]>)=>`<label class="form-row">${label}<select data-field="${name}">${options.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join('')}</select></label>`;
function inspector():void {
  el('inspector').querySelectorAll<HTMLDetailsElement>('[data-foldout]').forEach(d=>inspectorFoldouts.set(d.dataset.foldout!,d.open));
  const o=object(),r=region(),l=level(),group=(title:string,body:string,open=true)=>{const key=`${o?'object':r?'region':inspectorContext}:${title.split(' · ')[0]}`;return `<details class="inspector-group" data-foldout="${key}" ${(inspectorFoldouts.get(key)??open)?'open':''}><summary>${title}</summary>${body}</details>`;};
  let html='';
  if(selections.length>1){const b=selectionBounds(project,l,selections);html=group('Vị trí nhóm',`<div class="form-pair">${inputField('selectionX','X · mép trái',b.left,'number')}${inputField('selectionY','Y · mép trên',b.top,'number')}</div>`)+ '<p class="hint">Kéo để di chuyển cả cụm. Alt+bấm chọn riêng. Nhóm và căn chỉnh trong menu Chỉnh sửa.</p>';}
  else if(o){const a=project.assets.find(a=>a.id===o.assetId)!,p=o.pivot??a.pivot;
    html=`<button class="wide source-asset" data-inspect-asset="${a.id}">▧ ${esc(a.name)} · xem asset</button>`+inputField('name','Tên',o.name)+group('Transform',`<div class="form-pair">${inputField('x','X · điểm chân',o.x,'number')}${inputField('y','Y · điểm chân',o.y,'number')}</div><div class="form-pair">${inputField('scale','Tỷ lệ',o.scale,'number','min=".1" max="4" step=".1"')}${selectField('flipX','Lật ngang',String(o.flipX),[['false','Không'],['true','Có']])}</div>`)+group('Hiển thị',selectField('layerId','Layer thân/vật',o.layerId,l.layers.filter(l=>l.kind!=='regions').map(l=>[l.id,l.name]))+selectField('coverLayerId','Layer tán/mái',o.coverLayerId,l.layers.filter(l=>l.kind==='cover').map(l=>[l.id,l.name]))+inputField('opacity','Độ hiện',o.opacity,'number','min="0" max="1" step=".05"')+selectField('locked','Khóa đối tượng',String(o.locked),[['false','Không'],['true','Có']]))+group('Pivot',`<div class="form-pair">${inputField('pivotX','X trong hình',p.x,'number')}${inputField('pivotY','Y trong hình',p.y,'number')}</div><p class="hint">Điểm chân dùng để đặt hình và xếp lớp.</p>`,false);
  }else if(r){const activity=regionActivity(l,r),layer=l.layers.find(v=>v.id===r.layerId);html=`<div class="region-activity ${activity==='active'?'active':'inactive'}" data-region-activity="${activity}">${activity==='active'?'● Có hiệu lực trong Test':activity==='region-disabled'?'○ Vùng đang tắt · không có hiệu lực trong Test':`○ Không có hiệu lực: layer “${esc(layer?.name??'')}” đang tắt`}${activity==='layer-disabled'?`<button class="wide" data-enable-region-layer="${r.layerId}">Bật layer để vùng có hiệu lực</button>`:''}</div>`+inputField('name','Tên',r.name)+group('Vùng gameplay',selectField('kind','Loại',r.kind,[['walk','Vùng đi'],['block','Vùng chặn'],['portal','Cửa nối level']])+selectField('enabled','Hoạt động',String(r.enabled),[['true','Có'],['false','Không']])+selectField('layerId','Layer',r.layerId,l.layers.filter(l=>l.kind==='regions').map(l=>[l.id,l.name])));
    if(r.kind==='portal')html+=group('Điểm đến',selectField('targetLevelId','Level đích',r.targetLevelId,[['','Chưa chọn'],...project.levels.map(l=>[l.id,l.name] as [string,string])])+`<div class="form-pair">${inputField('targetX','X đến',r.target?.x??'','number')}${inputField('targetY','Y đến',r.target?.y??'','number')}</div><p class="hint">Để trống tọa độ để dùng Spawn của level đích.</p>`);
    html+=group(`Hình học · ${r.spline?'Spline':`${r.points.length} đỉnh`}`,selectField('geometry','Đường viền',r.spline?'spline':'polygon',[['polygon','Đa giác · cạnh thẳng'],['spline','Spline · đường cong']])+(r.spline?inputField('smoothness','Độ cong · 0 thẳng / 1 mềm',r.spline.smoothness,'number','min="0" max="1" step=".1"'):'')+`<p class="hint">V để chọn. Kéo điểm để sửa; Shift+bấm ${r.spline?'đường cong':'cạnh'} thêm điểm; Alt+bấm điểm xóa.</p><label class="form-row">${r.spline?'Điểm điều khiển':'Tọa độ'} x,y<textarea data-field="points">${controlPoints(r).map(p=>`${p.x},${p.y}`).join('\n')}</textarea></label>`,Boolean(r.spline));
  }else if(inspectorContext==='layer'){const layer=l.layers.find(x=>x.id===activeLayer);if(layer)html=inputField('layerName','Tên layer',layer.name)+selectField('layerKind','Loại layer',layer.kind,[['ground','Nền'],['decor','Trang trí thấp'],['depth','Theo chân'],['cover','Tán/mái'],['regions','Dữ liệu vùng']])+selectField('layerEnabled','Hoạt động trong game',String(layer.enabled),[['true','Có'],['false','Không']])+ '<p class="hint">Mắt: hiện trong editor. Khóa: tránh sửa nhầm. Hoạt động quyết định Test và runtime.</p>';}
  else {html=inputField('levelName','Tên level',l.name)+group('Kích thước',`<div class="form-pair">${inputField('width','Rộng · px',l.width,'number','min="64" max="8192"')}${inputField('height','Cao · px',l.height,'number','min="64" max="8192"')}</div>`+inputField('background','Màu nền',l.background,'color'))+group('Di chuyển',selectField('walkPolicy','Phạm vi đi',l.walkPolicy,[['full','Toàn level trừ vùng chặn'],['regions','Chỉ trong vùng đi']])+`<div class="form-pair">${inputField('spawnX','Spawn X',l.spawn.x,'number')}${inputField('spawnY','Spawn Y',l.spawn.y,'number')}</div>`);}
  el('inspector').innerHTML=html;el('inspector').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-field]').forEach(n=>n.disabled=playing);
  const locked=selections.some(s=>{const item=entity(l,s);return s.kind==='object'?Boolean(item&&((item as EditorObject).locked||objectLayerLocked(item as EditorObject))):Boolean(l.layers.find(x=>x.id===item?.layerId)?.locked);});
  if(locked)el('inspector').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[data-field]').forEach(n=>{if(n.dataset.field!=='locked'||o&&objectLayerLocked(o))n.disabled=true;});
}
function sceneTree():void {
  const l=level(),query=el<HTMLInputElement>('scene-search').value.toLocaleLowerCase('vi');
  el('layers').innerHTML=[...l.layers].reverse().map(layer=>{
    const items=[...l.objects.filter(o=>o.layerId===layer.id).map(o=>({id:o.id,kind:'object',name:o.name,tag:o.locked?'Khóa':o.groupId?'Nhóm':'',icon:'▧'})),...l.regions.filter(r=>r.layerId===layer.id).map(r=>({id:r.id,kind:'region',name:r.name,tag:regionActivity(l,r)!=='active'?'Tắt Test':r.groupId?'Nhóm':'',icon:r.kind==='walk'?'◇':r.kind==='block'?'▰':'↗'}))].filter(x=>x.name.toLocaleLowerCase('vi').includes(query));
    const row=`<div class="layer-row ${layer.id===activeLayer?'selected':''}" data-layer="${layer.id}"><button class="tree-fold" data-layer-collapse="${layer.id}" aria-label="Thu / mở ${esc(layer.name)}">${collapsedLayers.has(layer.id)?'›':'⌄'}</button><button data-layer-select="${layer.id}" title="${esc(layer.name)}">${esc(layer.name)}</button>${(['visible','locked','enabled'] as const).map((key,i)=>`<label data-flag="${key}" title="${['Hiện trong editor · không đổi va chạm','Khóa sửa','Hoạt động trong game · bật / tắt vật, va chạm và cửa nối'][i]}"><input aria-label="${['Hiện','Khóa','Hoạt động'][i]} ${esc(layer.name)}" type="checkbox" data-layer-flag="${key}" data-id="${layer.id}" ${layer[key]?'checked':''} />${layerIcons[i]}</label>`).join('')}</div>`;
    return `<div class="scene-layer">${row}<div class="scene-children" ${collapsedLayers.has(layer.id)&&!query?'hidden':''}>${items.map(x=>`<button class="entity ${selections.some(s=>s.id===x.id)?'selected':''}" data-entity="${x.id}" data-kind="${x.kind}"><i class="entity-icon">${x.icon}</i><span>${esc(x.name)}</span><small>${x.tag}</small></button>`).join('')}</div></div>`;
  }).join('');
}
function updateNavigationWarning():void {
  const l=level(),inactive=regionsOnDisabledLayers(l);
  el('navigation-warning').hidden=!inactive.length;
  if(inactive.length){const blocks=inactive.filter(r=>r.kind==='block').length;el('navigation-warning-text').textContent=`${inactive.length} vùng không có hiệu lực trong Test${blocks?` (${blocks} vùng chặn)`:''}: layer đang tắt Hoạt động trong game.`;}
  el('enable-region-layers').textContent=playing?'Dừng Test & bật layer':'Bật layer vùng';
}
function enableBlockedRegionLayers(layerId?:string):boolean {
  if(playing)testMode();
  const applied=edit(()=>{if(layerId){const layer=level().layers.find(l=>l.id===layerId);if(layer)layer.enabled=true;}else enableRegionLayers(level());});
  if(applied)status('Đã bật layer vùng. Vùng tắt riêng vẫn giữ trạng thái tắt; Ctrl+Z hoàn tác.');
  return applied;
}
function ui():void {
  if(!project)return;setSelection(selections);const l=level();el<HTMLInputElement>('project-name').value=project.name;
  el<HTMLSelectElement>('level').replaceChildren(...project.levels.map(x=>new Option(x.name,x.id)));el<HTMLSelectElement>('level').value=l.id;
  sceneTree();updateNavigationWarning();
  el('flows').innerHTML=project.levels.flatMap(a=>a.regions.filter(r=>r.kind==='portal').map(r=>{const dest=project.levels.find(l=>l.id===r.targetLevelId);return `<div class="flow ${dest?'':'warning'}">${esc(a.name)} → ${esc(dest?.name??'chưa chọn đích')}<br />${esc(r.name)} · ${regionActivity(a,r)==='active'?'hoạt động':'tắt trong Test'}</div>`;})).join('')||'<p class="hint">Chưa có cửa nối level.</p>';
  el<HTMLButtonElement>('undo').disabled=!undo.length||playing;el<HTMLButtonElement>('redo').disabled=!redo.length||playing;
  el('play').textContent=playing?'■ Dừng Test':'▶ Test map';document.body.classList.toggle('testing',playing);el('mode-label').textContent=playing?'TEST · WASD / mũi tên · E qua cửa':`${editDomain==='scene'?'SCENE':'NAVIGATION'} · ${l.name}`;
  el('layers').querySelectorAll<HTMLInputElement>('input').forEach(n=>n.disabled=playing);
  for(const id of ['project-name','new-project','add-level','clone-level','delete-level','duplicate','remove','add-layer','layer-up','layer-down','delete-layer','import-asset','import-project','import-level'])el<HTMLInputElement|HTMLButtonElement>(id).disabled=playing;
  el('counts').textContent=`${l.width} × ${l.height} · ${l.objects.length} vật · ${l.regions.length} vùng · ${selections.length} chọn`;palette();inspector();engineUi();refreshStudio();
}
function stamp(assetId:string,p:{x:number;y:number}):EditorObject|null {
  const a=project.assets.find(x=>x.id===assetId);if(!a||level().objects.length>=10000)return null;
  const current=level().layers.find(l=>l.id===activeLayer&&l.kind!=='regions'),base=current??level().layers.find(l=>l.kind===(a.defaultLayer??'depth')),cover=level().layers.find(l=>l.kind==='cover');
  if(!base||!cover||base.locked||(a.parts.some(p=>p.cover)&&cover.locked)){status('Cần layer đặt và Tán/Mái đã mở khóa.');return null;}
  const o:EditorObject={id:uid(),name:a.name,assetId:a.id,layerId:base.id,coverLayerId:cover.id,...p,scale:1,flipX:false,opacity:1,locked:false};level().objects.push(o);activeLayer=base.id;return o;
}
function place(assetId:string,p:{x:number;y:number}):void {if(playing)return;edit(()=>{const o=stamp(assetId,snapped(p));if(o)choose({kind:'object',id:o.id});});}
function splineSmoothness():number {return Math.max(0,Math.min(1,Number(el<HTMLInputElement>('spline-smoothness').value)||0));}
const controlPoints=(r:EditorRegion)=>r.spline?.anchors??r.points;
function addRegion(points:Array<{x:number;y:number}>):boolean {
  const l=level(),layer=l.layers.find(l=>l.id===activeLayer&&l.kind==='regions')??l.layers.find(l=>l.kind==='regions');if(!layer||layer.locked){status('Cần layer Vùng hoạt động đã mở khóa.');return false;}
  const kind=tool.startsWith('walk')?'walk':tool.startsWith('portal')?'portal':'block';
  return edit(()=>{const spline=tool.endsWith('spline')?{anchors:structuredClone(points),smoothness:splineSmoothness()}:undefined;const r:EditorRegion={id:uid(),name:kind==='walk'?'Vùng đi':kind==='block'?'Vùng chặn':'Cửa nối',kind,layerId:layer.id,points:spline?sampleSpline(spline.anchors,spline.smoothness):points,...(spline?{spline}:{}),enabled:true,targetLevelId:'',target:null};l.regions.push(r);choose({kind:'region',id:r.id});activeLayer=layer.id;});
}
const bounds=objectBounds;
function selectionCandidates():EntitySelection[] {const l=level(),solo=el<HTMLInputElement>('solo-layer').checked,visible=(id:string)=>l.layers.some(v=>v.id===id&&v.visible&&(!solo||id===activeLayer));
  const items:EntitySelection[]=[...l.objects.filter(o=>{const a=project.assets.find(a=>a.id===o.assetId);return !o.locked&&!objectLayerLocked(o)&&a?.parts.some(p=>visible(p.cover?o.coverLayerId:o.layerId));}).map(o=>({kind:'object' as const,id:o.id})),...l.regions.filter(r=>el<HTMLInputElement>('show-regions').checked&&visible(r.layerId)&&!l.layers.find(v=>v.id===r.layerId)?.locked).map(r=>({kind:'region' as const,id:r.id}))];
  return items.filter(s=>(editDomain==='scene'?s.kind==='object':s.kind==='region')&&groupMembers(l,s).every(m=>{const item=entity(l,m)!;return m.kind==='object'?!((item as EditorObject).locked||objectLayerLocked(item as EditorObject)):!l.layers.find(v=>v.id===item.layerId)?.locked;}));
}
function hit(p:{x:number;y:number}):Selection {
  const l=level();
  if(editDomain==='navigation'&&el<HTMLInputElement>('show-regions').checked){
    const area=(r:EditorRegion)=>Math.abs(r.points.reduce((total,p,i)=>{const q=r.points[(i+1)%r.points.length];return total+p.x*q.y-q.x*p.y;},0));
    const candidates=l.regions.map((r,index)=>({r,index})).filter(({r})=>{const layer=l.layers.find(x=>x.id===r.layerId);return layer?.visible&&!layer.locked&&(!el<HTMLInputElement>('solo-layer').checked||layer.id===activeLayer)&&inside(p,r.points);}).sort((a,b)=>area(a.r)-area(b.r)||b.index-a.index);
    if(candidates[0])return {kind:'region',id:candidates[0].r.id};
  }
  if(editDomain==='navigation'||p.x<0||p.y<0||p.x>l.width||p.y>l.height)return null;
  const rows=l.objects.flatMap((o,index)=>{if(objectLayerLocked(o)||o.locked)return [];const a=project.assets.find(a=>a.id===o.assetId)!;return a.parts.flatMap(part=>{const layer=l.layers.find(x=>x.id===(part.cover?o.coverLayerId:o.layerId));if(!layer?.visible||(el<HTMLInputElement>('solo-layer').checked&&layer.id!==activeLayer))return [];return [{o,a,part,index,band:layer.kind==='ground'?0:layer.kind==='decor'?1:2,order:l.layers.indexOf(layer),cover:part.cover||layer.kind==='cover'}];});});
  rows.sort((a,b)=>a.band-b.band||(a.band===2?a.o.y-b.o.y||Number(a.cover)-Number(b.cover):a.order-b.order)||a.index-b.index).reverse();
  for(const {o,a,part} of rows){const b=bounds(o,a);let x=Math.floor((p.x-b.left)/o.scale);const y=Math.floor((p.y-b.top)/o.scale);if(o.flipX)x=a.width-1-x;if(x<0||y<0||x>=a.width||y>=a.height)continue;if((images.get(part.file)?.mask.alpha[y*a.width+x]??0)>48)return {kind:'object',id:o.id};}
  return null;
}
canvas.addEventListener('dragover',e=>e.preventDefault());canvas.addEventListener('drop',e=>{e.preventDefault();setDomain('scene');place(e.dataTransfer?.getData('application/x-map-asset')??'',world(e));viewport.focus();});
el('palette').addEventListener('dragstart',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-asset]');if(b){(e as DragEvent).dataTransfer?.setData('application/x-map-asset',b.dataset.asset!);}});
el('palette').addEventListener('click',e=>{if(playing)return;const b=(e.target as HTMLElement).closest<HTMLElement>('[data-asset]');if(b){setDomain('scene');clearSelection();inspectorContext='asset';chosenAsset=b.dataset.asset!;chosenPrefab='';const a=project.assets.find(a=>a.id===chosenAsset)!;if(a.defaultLayer)activeLayer=level().layers.find(l=>l.kind===a.defaultLayer)?.id??activeLayer;if(a.category==='terrain'&&a.width===a.height)el<HTMLInputElement>('brush-step').value=String(a.width);setTool(['brush','paint-rect','erase'].includes(tool)?tool:'place');ui();}});
function brushStep():number {return Math.max(1,Math.min(2048,Number(el<HTMLInputElement>('brush-step').value)||32));}
function paintCell(p:{x:number;y:number}):void {const a=project.assets.find(a=>a.id===chosenAsset);if(!a)return;const base=level().layers.find(l=>l.id===activeLayer&&l.kind!=='regions')??level().layers.find(l=>l.kind===(a.defaultLayer??'depth')),cover=level().layers.find(l=>l.kind==='cover');if(!base||base.locked||!cover||(a.parts.some(p=>p.cover)&&cover.locked))return;
  const same=level().objects.filter(o=>o.layerId===base.id&&o.x===p.x&&o.y===p.y);if(same.some(o=>o.assetId===chosenAsset))return;
  if(a.category==='terrain'){const previous=same.filter(o=>project.assets.find(a=>a.id===o.assetId)?.category==='terrain');if(previous.some(o=>o.locked||objectLayerLocked(o)||o.groupId))return;const ids=new Set(previous.map(o=>o.id));level().objects=level().objects.filter(o=>!ids.has(o.id));}
  stamp(chosenAsset,p);
}
function brushPath(to:{x:number;y:number}):void {if(!drag||!['brush','erase'].includes(drag.mode))return;const step=brushStep();for(const p of gridStroke(drag.lastPoint??drag.start,to,step)){const key=`${p.x},${p.y}`;if(drag.seen!.has(key)||p.x<0||p.y<0||p.x>=level().width||p.y>=level().height)continue;drag.seen!.add(key);if(drag.mode==='erase'){level().objects=level().objects.filter(o=>o.layerId!==activeLayer||o.locked||objectLayerLocked(o)||o.groupId||Math.round(o.x/step)!==Math.round(p.x/step)||Math.round(o.y/step)!==Math.round(p.y/step));}else paintCell(p);}drag.lastPoint=to;}
canvas.addEventListener('pointerdown',e=>{
  if(!ready)return;viewport.focus();const p=world(e);hover=p;canvas.setPointerCapture(e.pointerId);
  if(e.button===1||space||tool==='pan'){e.preventDefault();drag={mode:'pan',start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),origin:{...view}};return;}
  if(e.button!==0||playing)return;
  if(tool==='place'){place(chosenAsset,p);return;}
  if(tool==='prefab'){const f=project.prefabs?.find(f=>f.id===chosenPrefab);if(f)edit(()=>setSelection(instantiatePrefab(project,level(),f,snapped(p))));return;}
  if(tool==='brush'||tool==='erase'){if(tool==='brush'&&!chosenAsset){status('Chọn asset trước khi dùng cọ.');return;}if(level().layers.find(l=>l.id===activeLayer)?.locked){status('Layer đang khóa.');return;}clearSelection();drag={mode:tool,start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),seen:new Set(),lastPoint:p};brushPath(p);return;}
  if(tool==='spawn'){edit(()=>level().spawn=snapped(p));return;}
  if(tool.endsWith('poly')||tool.endsWith('spline')){if(draft.length>=3&&Math.hypot(p.x-draft[0].x,p.y-draft[0].y)<=10/view.zoom){finish();return;}if(tool.endsWith('spline')&&draft.length>=MAX_SPLINE_ANCHORS){status(`Spline tối đa ${MAX_SPLINE_ANCHORS} điểm. Khép vùng hoặc chia thành vùng nhỏ hơn.`);return;}const point=snapped(p);if(!draft.length||point.x!==draft.at(-1)!.x||point.y!==draft.at(-1)!.y)draft.push(point);refreshStudio();return;}
  if(tool.endsWith('rect')){drag={mode:'rect',start:snapped(p),screen:{x:e.clientX,y:e.clientY},before:structuredClone(project)};return;}
  const r=editDomain==='navigation'?region():undefined,layer=r&&level().layers.find(l=>l.id===r.layerId),vertex=r&&selections.length===1&&!layer?.locked?controlPoints(r).findIndex(v=>Math.hypot(v.x-p.x,v.y-p.y)<10/view.zoom):-1;
  if(r&&vertex>=0&&e.altKey){if(controlPoints(r).length<=3){status('Vùng cần ít nhất 3 điểm.');return;}edit(()=>{controlPoints(r).splice(vertex,1);updateSplineRegion(r);});return;}
  if(r&&selections.length===1&&!layer?.locked&&e.shiftKey&&vertex<0){if(r.spline){const edge=nearestSplineEdge(r.spline,p);if(edge.distance<10/view.zoom){if(r.spline.anchors.length>=MAX_SPLINE_ANCHORS){status('Spline đã đạt giới hạn điểm.');return;}edit(()=>{r.spline!.anchors.splice(edge.index+1,0,snapped(edge.point));updateSplineRegion(r);});return;}}else {let edge=-1,best=10/view.zoom;for(let i=0;i<r.points.length;i++){const a=r.points[i],b=r.points[(i+1)%r.points.length],dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1))),distance=Math.hypot(p.x-a.x-dx*t,p.y-a.y-dy*t);if(distance<best){edge=i;best=distance;}}if(edge>=0){edit(()=>r.points.splice(edge+1,0,snapped(p)));return;}}}
  if(r&&vertex>=0){drag={mode:'vertex',start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),index:vertex};return;}
  const found=hit(p),additive=e.shiftKey||e.ctrlKey||e.metaKey;
  if(!found){if(!additive)clearSelection();drag={mode:'marquee',start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),additive,origin:[...selections]};ui();return;}
  if(additive||!selections.some(s=>entityKey(s)===entityKey(found)))choose(found,additive,e.altKey);else if(e.altKey)choose(found,false,true);
  activeLayer=object()?.layerId??region()?.layerId??activeLayer;ui();if(!selections.length||!canEditSelection())return;
  drag={mode:'selection',start:p,screen:{x:e.clientX,y:e.clientY},before:structuredClone(project),origin:structuredClone(level())};
});
canvas.addEventListener('pointermove',e=>{const p=world(e);hover=p;updateCoordinates();if(!drag)return;
  if(drag.mode==='pan'){view.x=drag.origin.x+e.clientX-drag.screen.x;view.y=drag.origin.y+e.clientY-drag.screen.y;return;}
  if(drag.mode==='selection'){for(const s of selections){const source=entity(drag.origin,s)!,dest=entity(level(),s)!;if(s.kind==='object'){const o=dest as EditorObject,v=source as EditorObject;o.x=v.x;o.y=v.y;}else {const r=dest as EditorRegion,origin=source as EditorRegion;r.points=structuredClone(origin.points);r.spline=origin.spline?structuredClone(origin.spline):undefined;}}translateEntities(level(),selections,snap(p.x-drag.start.x),snap(p.y-drag.start.y));alignmentGuides=[];if(el<HTMLInputElement>('magnet').checked&&!e.altKey){const moving=selectionBounds(project,level(),selections),selectedIds=new Set(selections.map(s=>s.id));const targets=editDomain==='navigation'?level().regions.filter(r=>!selectedIds.has(r.id)&&level().layers.some(l=>l.id===r.layerId&&l.visible&&(!el<HTMLInputElement>('solo-layer').checked||l.id===activeLayer))).map(r=>entityBounds(project,level(),{kind:'region',id:r.id})):level().objects.filter(o=>!selectedIds.has(o.id)&&level().layers.some(l=>l.id===o.layerId&&l.visible&&(!el<HTMLInputElement>('solo-layer').checked||l.id===activeLayer))).map(o=>bounds(o,project.assets.find(a=>a.id===o.assetId)!));targets.push({left:0,top:0,w:level().width,h:level().height});const result=alignWithGuides(moving,targets,6/view.zoom);translateEntities(level(),selections,result.dx,result.dy);alignmentGuides=result.guides;}}
  if(drag.mode==='vertex'){const r=region()!;controlPoints(r)[drag.index!]=snapped(p);try{updateSplineRegion(r);}catch(error){project=drag.before;drag=null;ui();status(String(error));return;}}
  if(drag.mode==='brush'||drag.mode==='erase')brushPath(p);
});
canvas.addEventListener('pointerup',e=>{if(!drag)return;const d=drag,p=world(e);drag=null;alignmentGuides=[];
  if(d.mode==='marquee'){const left=Math.min(d.start.x,p.x),top=Math.min(d.start.y,p.y),right=Math.max(d.start.x,p.x),bottom=Math.max(d.start.y,p.y);if(right-left>3||bottom-top>3){const candidates=selectionCandidates();const found=candidates.filter(s=>{const b=entityBounds(project,level(),s);return b.left<right&&b.left+b.w>left&&b.top<bottom&&b.top+b.h>top;}).flatMap(s=>groupMembers(level(),s));setSelection([...(d.additive?d.origin:[]),...found]);}ui();return;}
  if(d.mode==='rect'){const a=d.start,b=snapped(p);if(tool==='paint-rect'){const step=brushStep(),left=Math.ceil(Math.min(a.x,b.x)/step)*step,top=Math.ceil(Math.min(a.y,b.y)/step)*step,right=Math.floor(Math.max(a.x,b.x)/step)*step,bottom=Math.floor(Math.max(a.y,b.y)/step)*step,count=(1+(right-left)/step)*(1+(bottom-top)/step);if(!chosenAsset){status('Chọn asset trước khi tô ô.');return;}if(count>2000){status('Mỗi lượt tô tối đa 2000 ô. Chia vùng nhỏ hơn.');return;}edit(()=>{for(let y=top;y<=bottom;y+=step)for(let x=left;x<=right;x+=step)if(x>=0&&y>=0&&x<level().width&&y<level().height)paintCell({x,y});});}
    else if(Math.abs(a.x-b.x)>=4&&Math.abs(a.y-b.y)>=4)addRegion([{x:a.x,y:a.y},{x:b.x,y:a.y},{x:b.x,y:b.y},{x:a.x,y:b.y}]);}
  else if(d.mode!=='pan'&&JSON.stringify(d.before.levels)!==JSON.stringify(project.levels))changed(d.before);ui();
});
canvas.addEventListener('pointercancel',()=>{if(drag&&drag.mode!=='pan'&&drag.mode!=='marquee')project=drag.before;drag=null;alignmentGuides=[];ui();});
canvas.addEventListener('wheel',e=>{e.preventDefault();const b=canvas.getBoundingClientRect();zoomTo(view.zoom*(e.deltaY<0?1.15:1/1.15),{x:e.clientX-b.left,y:e.clientY-b.top});},{passive:false});
const finish=()=>{if(draft.length>=3){if(addRegion([...draft])){setTool('select');ui();}}else status('Cần ít nhất 3 đỉnh.');};
el('finish-polygon').addEventListener('click',finish);document.querySelectorAll<HTMLElement>('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool!)));
function canEditSelection():boolean {for(const s of selections){const item=entity(level(),s);if(s.kind==='object'&&item&&((item as EditorObject).locked||objectLayerLocked(item as EditorObject))||s.kind==='region'&&item&&level().layers.find(l=>l.id===item.layerId)?.locked){status('Có đối tượng hoặc layer đang khóa. Mở khóa trước khi sửa cả lựa chọn.');return false;}}return true;}
function remove():void {if(!selections.length||!canEditSelection())return;edit(()=>{const objects=new Set(selections.filter(s=>s.kind==='object').map(s=>s.id)),regions=new Set(selections.filter(s=>s.kind==='region').map(s=>s.id));level().objects=level().objects.filter(o=>!objects.has(o.id));level().regions=level().regions.filter(r=>!regions.has(r.id));clearSelection();});}
function cloneLibraryAsset(id=chosenAsset,inspect=true):EditorAsset {
  if(playing)throw new Error('Dừng Test để nhân bản asset.');
  if(project.assets.length>=200)throw new Error('Thư viện tối đa 200 asset.');
  if(!project.assets.some(a=>a.id===id))throw new Error('Chọn asset trong thư viện để nhân bản.');
  let copy:EditorAsset|undefined;
  const applied=edit(()=>{copy=duplicateAsset(project,id);const thumbnail=thumbnails.get(id);if(thumbnail)thumbnails.set(copy.id,thumbnail);if(inspect){clearSelection();chosenAsset=copy.id;chosenPrefab='';inspectorContext='asset';}});
  if(!applied||!copy)throw new Error('Không nhân bản được asset. Kiểm giới hạn thư viện / dữ liệu.');
  if(inspect){setTool('select');ui();}status(`Đã tạo “${copy.name}”. Bản sao độc lập trong Assets; Ctrl+S lưu, Ctrl+Z hoàn tác.`);
  return copy;
}
function duplicate():void {if(inspectorContext==='asset'&&!selections.length){try{cloneLibraryAsset();}catch(error){status((error as Error).message);}return;}if(!selections.length||!canEditSelection())return;edit(()=>setSelection(duplicateEntities(level(),selections)));}
function history(back:boolean):void {if(playing)return;el('issues').innerHTML='<p class="hint">Bấm Kiểm tra để cập nhật sau undo/redo.</p>';const from=back?undo:redo,to=back?redo:undo,p=from.pop();if(p){to.push(structuredClone(project));project=p;clearSelection();if(!level().layers.some(l=>l.id===activeLayer))activeLayer=level().layers.find(l=>l.kind==='depth')?.id??level().layers[0].id;studio.saveState(JSON.stringify(project)===savedProjectJSON?'Đã lưu vào dự án':'Có thay đổi · chưa lưu file',JSON.stringify(project)===savedProjectJSON?'saved':'dirty');ui();localSave();void loadAssets();}}
function testMode(allowDisabledLayers=false):void {if(playing){playing=false;keys.clear();if(editView?.levelId===level().id){view={...editView.view};el<HTMLInputElement>('zoom').value=String(Math.round(view.zoom*100)/100);updateCoordinates();}else fit();el<HTMLInputElement>('show-regions').checked=true;ui();status('Trở lại biên tập.');return;}const inactive=regionsOnDisabledLayers(level());if(inactive.length&&!allowDisabledLayers){const groups=level().layers.filter(l=>inactive.some(r=>r.layerId===l.id));el('navigation-test-explanation').textContent=`${inactive.length} vùng đã bật nhưng nằm trên layer đang tắt. Nếu tiếp tục, Test sẽ bỏ qua va chạm / đường đi / cửa nối của các vùng này.`;el('navigation-test-layers').innerHTML=groups.map(l=>`<li><strong>${esc(l.name)}</strong> · ${inactive.filter(r=>r.layerId===l.id).map(r=>`${esc(r.name)} (${r.kind==='block'?'chặn':r.kind==='walk'?'đi':'cửa'})`).join(', ')}</li>`).join('');el<HTMLDialogElement>('navigation-test-dialog').showModal();return;}if(!editorWalkable(level(),level().spawn)){status('Spawn đang bị chặn hoặc chưa có vùng đi. Chỉnh Spawn / vẽ vùng đi trước khi Test.');return;}editView={levelId:level().id,view:{...view}};view.zoom=1;el<HTMLInputElement>('zoom').value='1';playing=true;clearSelection();draft=[];player={...level().spawn,direction:'south',moving:false};animation.set('stand','south');keys.clear();el<HTMLInputElement>('show-regions').checked=false;ui();viewport.focus();status('WASD / mũi tên để đi; E qua cửa nối; Esc dừng.');}
function traverse():void {const result=portalAt(project,level(),player);if(!result){status('Không ở trong cửa hợp lệ, hoặc level đích/vị trí đến chưa đi được.');return;}project.activeLevelId=result.level.id;player={...result.point,direction:player.direction,moving:false};ui();status(`Đã qua cửa: ${result.level.name}`);}
el('play').addEventListener('click',()=>testMode());
el('enable-region-layers').addEventListener('click',()=>enableBlockedRegionLayers());
el('navigation-test-cancel').addEventListener('click',()=>el<HTMLDialogElement>('navigation-test-dialog').close());
el('navigation-test-current').addEventListener('click',()=>{el<HTMLDialogElement>('navigation-test-dialog').close();testMode(true);});
el('navigation-test-enable').addEventListener('click',()=>{el<HTMLDialogElement>('navigation-test-dialog').close();if(enableBlockedRegionLayers())testMode();});el('remove').addEventListener('click',remove);el('duplicate').addEventListener('click',duplicate);el('undo').addEventListener('click',()=>history(true));el('redo').addEventListener('click',()=>history(false));
el('fit').addEventListener('click',fit);el('native').addEventListener('click',()=>zoomTo(1));el<HTMLInputElement>('zoom').addEventListener('change',()=>zoomTo(Number(el<HTMLInputElement>('zoom').value)));
el<HTMLSelectElement>('level').addEventListener('change',()=>{const select=el<HTMLSelectElement>('level'),next=project.levels.find(l=>l.id===select.value)!;if(playing&&!editorWalkable(next,next.spawn)){select.value=project.activeLevelId;status('Spawn của level này chưa đi được. Dừng Test để chỉnh.');return;}activate(select.value);});
el('add-level').addEventListener('click',()=>edit(()=>{const l=newLevel(`Level ${project.levels.length+1}`);project.levels.push(l);project.activeLevelId=l.id;clearSelection();activeLayer=l.layers[2].id;fit();}));
el('clone-level').addEventListener('click',()=>edit(()=>{const l=structuredClone(level()),old=l.id,ids=new Map(l.layers.map(x=>[x.id,uid()]));l.id=uid();l.name+=' (bản sao)';for(const layer of l.layers)layer.id=ids.get(layer.id)!;for(const o of l.objects){o.id=uid();o.layerId=ids.get(o.layerId)!;o.coverLayerId=ids.get(o.coverLayerId)!;}for(const r of l.regions){r.id=uid();r.layerId=ids.get(r.layerId)!;if(r.targetLevelId===old)r.targetLevelId=l.id;}project.levels.push(l);project.activeLevelId=l.id;clearSelection();activeLayer=l.layers[2]?.id??l.layers[0].id;}));
el('delete-level').addEventListener('click',()=>{if(project.levels.length<2){status('Dự án cần ít nhất một level.');return;}edit(()=>{const id=level().id;project.levels=project.levels.filter(l=>l.id!==id);project.activeLevelId=project.levels[0].id;clearSelection();activeLayer=level().layers[2]?.id??level().layers[0].id;for(const l of project.levels)for(const r of l.regions)if(r.targetLevelId===id)r.targetLevelId='';fit();});});
el('layers').addEventListener('click',e=>{const fold=(e.target as HTMLElement).closest<HTMLElement>('[data-layer-collapse]');if(fold){const id=fold.dataset.layerCollapse!;if(collapsedLayers.has(id))collapsedLayers.delete(id);else collapsedLayers.add(id);sceneTree();return;}const b=(e.target as HTMLElement).closest<HTMLElement>('[data-layer-select]');if(b){if(playing)return;activeLayer=b.dataset.layerSelect!;const kind=level().layers.find(l=>l.id===activeLayer)?.kind;editDomain=kind==='regions'?'navigation':'scene';clearSelection();inspectorContext='layer';tool='select';draft=[];ui();}});
el('layers').addEventListener('change',e=>{const n=e.target as HTMLInputElement;if(n.dataset.layerFlag)edit(()=>{const l=level().layers.find(l=>l.id===n.dataset.id)!;l[n.dataset.layerFlag as 'visible'|'locked'|'enabled']=n.checked;});});
el('add-layer').addEventListener('click',()=>edit(()=>{const l={id:uid(),name:'Layer mới',kind:'depth' as LayerKind,visible:true,locked:false,enabled:true};level().layers.push(l);activeLayer=l.id;clearSelection();}));
for(const[id,delta]of [['layer-up',1],['layer-down',-1]] as const)el(id).addEventListener('click',()=>edit(()=>{const list=level().layers,i=list.findIndex(l=>l.id===activeLayer),j=i+delta;if(j>=0&&j<list.length)[list[i],list[j]]=[list[j],list[i]];}));
el('delete-layer').addEventListener('click',()=>{if(level().objects.some(o=>o.layerId===activeLayer||o.coverLayerId===activeLayer)||level().regions.some(r=>r.layerId===activeLayer)||level().layers.length===1){status('Layer còn đối tượng/vùng tham chiếu. Chuyển chúng sang layer khác trước.');return;}edit(()=>{level().layers=level().layers.filter(l=>l.id!==activeLayer);activeLayer=level().layers[0].id;});});
el('entities').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-entity]');if(b){editDomain=b.dataset.kind==='region'?'navigation':'scene';choose({kind:b.dataset.kind as 'object'|'region',id:b.dataset.entity!},(e as MouseEvent).shiftKey||(e as MouseEvent).ctrlKey,(e as MouseEvent).altKey);activeLayer=object()?.layerId??region()?.layerId??activeLayer;setTool('select');ui();}});
el('inspector').addEventListener('click',e=>{const enable=(e.target as HTMLElement).closest<HTMLElement>('[data-enable-region-layer]');if(enable){if(!playing)enableBlockedRegionLayers(enable.dataset.enableRegionLayer);return;}const b=(e.target as HTMLElement).closest<HTMLElement>('[data-inspect-asset]');if(!b||playing)return;chosenAsset=b.dataset.inspectAsset!;clearSelection();inspectorContext='asset';ui();});
el('inspector').addEventListener('change',e=>{const n=e.target as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement,key=n.dataset.field;if(!key)return;edit(()=>{const o=object(),r=region(),l=level();if(key==='selectionX'||key==='selectionY'){if(!canEditSelection())return;const b=selectionBounds(project,l,selections);translateEntities(l,selections,key==='selectionX'?Number(n.value)-b.left:0,key==='selectionY'?Number(n.value)-b.top:0);}else if(o){if(key==='pivotX'||key==='pivotY'){o.pivot??={...project.assets.find(a=>a.id===o.assetId)!.pivot};o.pivot[key==='pivotX'?'x':'y']=Number(n.value);}else if(['x','y','scale','opacity'].includes(key))(o as any)[key]=Number(n.value);else if(['flipX','locked'].includes(key))(o as any)[key]=n.value==='true';else(o as any)[key]=n.value;}
  else if(r){if(key==='points'){const points=n.value.trim().split('\n').map(s=>{const[x,y]=s.split(',').map(Number);return {x,y};});if(r.spline){r.spline.anchors=points;updateSplineRegion(r);}else r.points=points;}else if(key==='geometry'){if(n.value==='spline'&&!r.spline){if(r.points.length>MAX_SPLINE_ANCHORS)throw new Error('Vùng có quá nhiều đỉnh để chuyển trực tiếp. Giảm điểm hoặc vẽ spline mới.');r.spline={anchors:structuredClone(r.points),smoothness:1};updateSplineRegion(r);}else if(n.value==='polygon'&&r.spline){r.points=structuredClone(r.spline.anchors);delete r.spline;}}else if(key==='smoothness'&&r.spline){r.spline.smoothness=Number(n.value);updateSplineRegion(r);}else if(key==='enabled')r.enabled=n.value==='true';else if(key==='targetX'||key==='targetY'){if(n.value==='')r.target=null;else{const dest=project.levels.find(l=>l.id===r.targetLevelId);r.target??={...(dest?.spawn??{x:0,y:0})};r.target[key==='targetX'?'x':'y']=Number(n.value);}}else(r as any)[key]=n.value;}
  else {if(key==='levelName')l.name=n.value;else if(['width','height'].includes(key))(l as any)[key]=Number(n.value);else if(key==='spawnX'||key==='spawnY')l.spawn[key==='spawnX'?'x':'y']=Number(n.value);else if(key==='layerName')l.layers.find(l=>l.id===activeLayer)!.name=n.value;else if(key==='layerKind')l.layers.find(l=>l.id===activeLayer)!.kind=n.value as LayerKind;else if(key==='layerEnabled')l.layers.find(l=>l.id===activeLayer)!.enabled=n.value==='true';else(l as any)[key]=n.value;}});});
el('scene-search').addEventListener('input',sceneTree);el('level-settings').addEventListener('click',()=>{clearSelection();ui();});
el('search').addEventListener('input',palette);el('project-name').addEventListener('change',()=>edit(()=>project.name=el<HTMLInputElement>('project-name').value));
el('save').addEventListener('click',()=>void save());el('export').addEventListener('click',()=>download(`${project.id}.project.json`,project));el('export-level').addEventListener('click',()=>download(`${level().id}.level.json`,exportEditorLevel(project,level())));
el('new-project').addEventListener('click',()=>{if(playing)return;localSave();project=newProject(project.assets);savedProjectJSON='';chosenAsset='';chosenPrefab='';editDomain='scene';tool='select';draft=[];clearSelection();activeLayer=level().layers[2].id;undo.length=redo.length=0;fit();ui();localSave();studio.saveState('Dự án mới · chưa lưu file','draft');void savedList();el('issues').innerHTML='<p class="hint">Bấm Kiểm tra để kiểm level mới.</p>';status('Dự án trống đã tạo. Bản nháp trước vẫn có trong Mở bản lưu.');});
async function openProject(p:EditorProject):Promise<void>{await loadAssets(p);localSave();project=p;savedProjectJSON='';chosenAsset='';chosenPrefab='';editDomain='scene';tool='select';draft=[];clearSelection();undo.length=redo.length=0;playing=false;activate(p.activeLevelId);studio.saveState('Bản đang mở · Ctrl+S để lưu file','draft');el('issues').innerHTML='<p class="hint">Bấm Kiểm tra để kiểm dự án vừa mở.</p>';status('Đã mở dự án.');}
el<HTMLSelectElement>('saved-projects').addEventListener('change',async()=>{const value=el<HTMLSelectElement>('saved-projects').value;if(!value)return;try{const raw=value.startsWith('draft:')?JSON.parse(localStorage.getItem(`game-solo-map-editor:${value.slice(6)}`)!):await(await fetch(`/api/map-editor/projects/${value}`)).json();await openProject(parseProject(raw));if(!value.startsWith('draft:')){savedProjectJSON=JSON.stringify(project);studio.saveState('Đã mở file dự án đã lưu','saved');}}catch(error){status(String(error));}});
el<HTMLInputElement>('import-project').addEventListener('change',async e=>{const n=e.target as HTMLInputElement,file=n.files?.[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('JSON vượt20 MB.');await openProject(parseProject(JSON.parse(await file.text())));}catch(error){status(String(error));}n.value='';});
el<HTMLInputElement>('import-level').addEventListener('change',async e=>{const n=e.target as HTMLInputElement,file=n.files?.[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('JSON vượt20 MB.');await openProject(mergeEditorLevel(project,JSON.parse(await file.text())));}catch(error){status(String(error));}n.value='';});
async function addAssets(assets:EditorAsset[]):Promise<void> {if(project.assets.length+assets.length>200)throw new Error('Thư viện tối đa 200 asset.');const next=structuredClone(project);next.assets.push(...assets);await loadAssets(next);setDomain('scene');clearSelection();inspectorContext='asset';edit(()=>{project.assets.push(...assets);chosenAsset=assets[0]?.id??chosenAsset;chosenPrefab='';if(assets[0]?.defaultLayer)activeLayer=level().layers.find(l=>l.kind===assets[0].defaultLayer)?.id??activeLayer;});setTool('place');ui();status(`Đã nhập ${assets.length} ảnh. Chỉnh pivot và layer mặc định ở Thuộc tính asset.`);}
el<HTMLInputElement>('import-asset').addEventListener('change',async e=>{const n=e.target as HTMLInputElement;try{if(playing)return;await addAssets(await importImages(Array.from(n.files??[])));}catch(error){status(String(error));}n.value='';});
el<HTMLInputElement>('import-tileset').addEventListener('change',async e=>{const n=e.target as HTMLInputElement;try{if(!playing&&n.files?.[0])await addAssets(await sliceTileset(n.files[0],Number(el<HTMLInputElement>('tile-width').value),Number(el<HTMLInputElement>('tile-height').value),200-project.assets.length));}catch(error){status(String(error));}n.value='';});
window.addEventListener('keydown',e=>{if(!ready||document.querySelector('dialog[open]'))return;const form=/INPUT|SELECT|TEXTAREA/.test((e.target as HTMLElement)?.tagName),key=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&key==='s'){e.preventDefault();void save();return;}if(form)return;
  if(key==='escape'){if(playing)testMode();else{draft=[];if(drag&&drag.mode!=='pan'&&drag.mode!=='marquee')project=drag.before;drag=null;alignmentGuides=[];setTool('select');ui();}return;}
  if(playing){if(key==='e'&&!e.repeat){traverse();return;}if(['w','a','s','d','arrowup','arrowleft','arrowdown','arrowright'].includes(key)){e.preventDefault();keys.add(key);}return;}
  if(key==='backspace'&&draft.length){e.preventDefault();draft.pop();refreshStudio();return;}
  if((e.ctrlKey||e.metaKey)&&key==='a'){e.preventDefault();selectAll();return;}if((e.ctrlKey||e.metaKey)&&key==='g'){e.preventDefault();groupSelection(e.shiftKey);return;}if((e.ctrlKey||e.metaKey)&&key==='c'){e.preventDefault();copySelection();return;}if((e.ctrlKey||e.metaKey)&&key==='v'){e.preventDefault();pasteSelection();return;}
  if(['arrowup','arrowdown','arrowleft','arrowright'].includes(key)&&selections.length){e.preventDefault();if(canEditSelection()){const step=Number(el<HTMLSelectElement>('snap').value)*(e.shiftKey?10:1);edit(()=>translateEntities(level(),selections,key==='arrowleft'?-step:key==='arrowright'?step:0,key==='arrowup'?-step:key==='arrowdown'?step:0));}return;}
  if(key==='f'){frameSelection();return;}if(key==='b'){setTool('brush');return;}
  if((e.ctrlKey||e.metaKey)&&key==='z'){e.preventDefault();history(!e.shiftKey);}else if((e.ctrlKey||e.metaKey)&&key==='d'){e.preventDefault();duplicate();}else if(key==='delete'||key==='backspace'){e.preventDefault();remove();}else if(key==='enter'&&draft.length)finish();else if(key==='v')setTool('select');else if(key==='h')setTool('pan');else if(key===' '){e.preventDefault();space=true;}
});
window.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key===' ')space=false;});window.addEventListener('blur',()=>{keys.clear();space=false;});window.addEventListener('pagehide',()=>{if(project)localSave();});
function shape(points:Array<{x:number;y:number}>,fill:string,stroke:string,width=1):void {if(!points.length)return;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(const p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=width/view.zoom;ctx.stroke();}
function render(now:number):void {
  const dt=Math.min(.25,(now-last)/1000);last=now;requestAnimationFrame(render);if(!ready)return;
  const l=level();if(now-lastMinimap>180){drawMinimap();lastMinimap=now;}if(playing){const next=moveInEditor(l,player,{x:Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),y:Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'))},dt);const distance=Math.hypot(next.x-player.x,next.y-player.y);player=next;animation.updateFromTravel(distance,player.direction,player.moving,24);view.x=viewport.clientWidth/2-player.x*view.zoom;view.y=viewport.clientHeight/2-player.y*view.zoom;}
  const dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(viewport.clientWidth*dpr)||canvas.height!==Math.round(viewport.clientHeight*dpr)){canvas.width=Math.round(viewport.clientWidth*dpr);canvas.height=Math.round(viewport.clientHeight*dpr);}
  ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,canvas.width/dpr,canvas.height/dpr);ctx.translate(view.x,view.y);ctx.scale(view.zoom,view.zoom);ctx.fillStyle=l.background;ctx.fillRect(0,0,l.width,l.height);ctx.save();ctx.beginPath();ctx.rect(0,0,l.width,l.height);ctx.clip();
  const objectOrder=new Map(l.objects.map((o,i)=>[o.id,i]));const rows:Array<{o:EditorObject;a:EditorAsset;part:EditorAsset['parts'][number];band:number;order:number;cover:boolean}>=[];
  for(const o of l.objects){const a=project.assets.find(a=>a.id===o.assetId);if(!a)continue;const box=bounds(o,a);if((box.left+box.w)*view.zoom+view.x<0||box.left*view.zoom+view.x>viewport.clientWidth||(box.top+box.h)*view.zoom+view.y<0||box.top*view.zoom+view.y>viewport.clientHeight)continue;for(const part of a.parts){const layer=l.layers.find(x=>x.id===(part.cover?o.coverLayerId:o.layerId));const base=l.layers.find(x=>x.id===o.layerId);if(!layer||(!playing&&(!layer.visible||(el<HTMLInputElement>('solo-layer').checked&&layer.id!==activeLayer)))||(playing&&(!layer.enabled||!base?.enabled)))continue;rows.push({o,a,part,band:layer.kind==='ground'?0:layer.kind==='decor'?1:2,order:l.layers.indexOf(layer),cover:part.cover||layer.kind==='cover'});}}
  rows.sort((a,b)=>a.band-b.band||(a.band===2?a.o.y-b.o.y||Number(a.cover)-Number(b.cover):a.order-b.order)||objectOrder.get(a.o.id)!-objectOrder.get(b.o.id)!);
  const frame=playing?atlas.frames[animation.frameId]:null;
  if(frame&&!actorFrameMasks.has(animation.frameId))actorFrameMasks.set(animation.frameId,cropAlpha(actorSourceMask,frame));
  const actorMask=frame?actorFrameMasks.get(animation.frameId)!:null;
  const drawActor=()=>{if(!frame)return;ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(actorImage,frame.x,frame.y,frame.w,frame.h,player.x-32,player.y-88,64,96);ctx.restore();};
  let actorDrawn=false;
  for(const row of rows){if(playing&&!actorDrawn&&row.band===2&&row.o.y>player.y){drawActor();actorDrawn=true;}const {o,a,part}=row,img=images.get(part.file);if(!img)continue;const b=bounds(o,a),layer=l.layers[row.order];ctx.save();ctx.imageSmoothingEnabled=false;ctx.globalAlpha=o.opacity*(layer.enabled?1:.3);
    if(playing&&row.cover&&player.y<o.y&&actorMask&&opaqueMasksOverlap({mask:img.mask,left:b.left,top:b.top,scaleX:o.scale,scaleY:o.scale,flipX:o.flipX},{mask:actorMask,left:player.x-32,top:player.y-88}))ctx.globalAlpha*=.35;
    if(o.flipX){ctx.translate(b.left+b.w,b.top);ctx.scale(-1,1);ctx.drawImage(img.image,0,0,b.w,b.h);}else ctx.drawImage(img.image,b.left,b.top,b.w,b.h);ctx.restore();}
  if(playing&&!actorDrawn)drawActor();ctx.restore();
  if(!playing&&el<HTMLInputElement>('grid').checked){const step=Math.max(16,Number(el<HTMLSelectElement>('snap').value)),left=Math.max(0,Math.floor((-view.x/view.zoom)/step)*step),top=Math.max(0,Math.floor((-view.y/view.zoom)/step)*step),right=Math.min(l.width,(-view.x+viewport.clientWidth)/view.zoom),bottom=Math.min(l.height,(-view.y+viewport.clientHeight)/view.zoom);ctx.strokeStyle='#21382b25';ctx.lineWidth=1/view.zoom;ctx.beginPath();for(let x=left;x<=right;x+=step){ctx.moveTo(x,Math.max(0,top));ctx.lineTo(x,bottom);}for(let y=top;y<=bottom;y+=step){ctx.moveTo(left,y);ctx.lineTo(right,y);}ctx.stroke();}
  if(el<HTMLInputElement>('show-regions').checked)for(const r of l.regions){if(!l.layers.find(x=>x.id===r.layerId)?.visible||(el<HTMLInputElement>('solo-layer').checked&&r.layerId!==activeLayer))continue;const active=regionActivity(l,r)==='active',color=!active?'#9a9fa9':r.kind==='walk'?'#54b57d':r.kind==='block'?'#e76c60':'#ab87ef';ctx.save();if(!active)ctx.setLineDash([6/view.zoom,4/view.zoom]);shape(r.points,color+(editDomain==='navigation'?'30':'08'),color+(editDomain==='navigation'?'ff':'50'),selected?.id===r.id?2:1);ctx.restore();if(selected?.id===r.id&&!playing)for(const p of controlPoints(r)){ctx.beginPath();ctx.arc(p.x,p.y,5/view.zoom,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.stroke();}}
  if(!playing){ctx.strokeStyle='#d4e5ae';ctx.lineWidth=2/view.zoom;for(const s of selections){if(selections.length===1&&s.kind==='region')continue;const b=entityBounds(project,l,s);ctx.strokeRect(b.left,b.top,b.w,b.h);}const o=object();if(o){ctx.beginPath();ctx.moveTo(o.x-8/view.zoom,o.y);ctx.lineTo(o.x+8/view.zoom,o.y);ctx.moveTo(o.x,o.y-8/view.zoom);ctx.lineTo(o.x,o.y+8/view.zoom);ctx.stroke();}
    const ghost=project.assets.find(a=>a.id===chosenAsset);if(ghost&&['place','brush','paint-rect'].includes(tool)){const p=tool==='place'?snapped(hover):gridStroke(hover,hover,brushStep())[0];const b=bounds({x:p.x,y:p.y,scale:1,flipX:false} as EditorObject,ghost);ctx.save();ctx.globalAlpha=.45;ctx.imageSmoothingEnabled=false;for(const part of ghost.parts){const img=images.get(part.file);if(img)ctx.drawImage(img.image,b.left,b.top,b.w,b.h);}ctx.restore();}
    ctx.beginPath();ctx.arc(l.spawn.x,l.spawn.y,8,0,Math.PI*2);ctx.strokeStyle='#324eac';ctx.stroke();ctx.fillStyle='#233974';ctx.font=`${11/view.zoom}px Segoe UI`;ctx.fillText('Spawn',l.spawn.x+12,l.spawn.y);
    if(draft.length){let preview=[...draft];const next=snapped(hover),closing=draft.length>=3&&Math.hypot(hover.x-draft[0].x,hover.y-draft[0].y)<10/view.zoom;if(!closing&&draft.length<MAX_SPLINE_ANCHORS&&(next.x!==draft.at(-1)!.x||next.y!==draft.at(-1)!.y))preview.push(next);if(tool.endsWith('spline')&&preview.length>1){try{preview=sampleSpline(preview,splineSmoothness(),closing||preview.length>=3);}catch{/* A committed region reports limits through edit(). */}}shape(preview,'#8ab9ed25','#9bc9ff');for(let i=0;i<draft.length;i++){const p=draft[i];ctx.beginPath();ctx.arc(p.x,p.y,(i===0?6:4)/view.zoom,0,Math.PI*2);ctx.fillStyle=i===0?'#91c5ff':'#d9eaff';ctx.fill();}ctx.fillStyle='#b9d8ff';ctx.font=`${11/view.zoom}px Segoe UI`;ctx.fillText(`${draft.length} đỉnh`,draft[0].x+12/view.zoom,draft[0].y-10/view.zoom);}if(drag?.mode==='rect'||drag?.mode==='marquee'){const a=drag.start,b=snapped(hover);shape([a,{x:b.x,y:a.y},b,{x:a.x,y:b.y}],'#e6e2ac35','#e8e9b1');}
    if(alignmentGuides.length){ctx.save();ctx.strokeStyle='#81dfd4';ctx.lineWidth=1/view.zoom;ctx.setLineDash([5/view.zoom,4/view.zoom]);for(const guide of alignmentGuides){ctx.beginPath();if(guide.axis==='x'){ctx.moveTo(guide.value,0);ctx.lineTo(guide.value,l.height);}else{ctx.moveTo(0,guide.value);ctx.lineTo(l.width,guide.value);}ctx.stroke();}ctx.restore();}}
}
async function init():Promise<void>{
  const kit=await(await fetch('/assets/map-kit/manifest.json',{cache:'no-store'})).json();const assets:EditorAsset[]=kit.assets.map((a:any)=>({id:a.id,name:a.label,width:a.width,height:a.height,pivot:{x:a.suggestedPivot[0],y:a.suggestedPivot[1]},parts:a.layers.map((p:any)=>({id:p.id,file:`/assets/map-kit/${p.file}`,cover:p.role==='optional_occluder'}))}));
  for(const a of assets)for(const part of a.parts)libraryFiles.add(part.file);
  const revision=String(kit.libraryRevision??kit.version),revisionKey='game-solo-map-editor-library-revision';let libraryReset=localStorage.getItem(revisionKey)!==revision;
  const lastId=localStorage.getItem('game-solo-map-editor-last');try{project=!libraryReset&&lastId?parseProject(JSON.parse(localStorage.getItem(`game-solo-map-editor:${lastId}`)!)):newProject(assets);}catch{project=newProject(assets);libraryReset=true;}
  if(project.assets.some(a=>a.parts.some(p=>p.file.startsWith('/assets/map-kit/')&&!libraryFiles.has(p.file)))){project=newProject(assets);libraryReset=true;}
  activeLayer=level().layers.find(l=>l.kind==='depth')?.id??level().layers[0].id;
  const catalog=await(await fetch('/assets/catalog.json',{cache:'no-store'})).json(),actor=catalog.actors.find((a:any)=>a.id==='AVATAR-NOVICE-MALE');atlas=normalizeAtlas(await(await fetch(actor.metadataUrl)).json());animation=new AnimationPlayer(atlas);actorImage=new Image();actorImage.src=actor.atlasUrl;
  await Promise.all([loadAssets(),actorImage.decode()]);actorSourceMask=imageAlpha(actorImage);ready=true;document.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement|HTMLTextAreaElement>('input,button,select,textarea').forEach(n=>n.disabled=false);fit();ui();
  if(libraryReset){localSave();localStorage.setItem(revisionKey,revision);}
  studio.saveState('Nháp trình duyệt · Ctrl+S lưu file','draft');await savedList();status(libraryReset?'Đã mở dự án trống với thư viện mới. Bản nháp trước vẫn có trong Mở bản lưu.':'Sẵn sàng. Nhập PNG/WebP hoặc kéo asset để biên tập map.');
}
function selectAll():void {if(playing)return;setSelection(selectionCandidates().flatMap(s=>groupMembers(level(),s)));ui();}
function groupSelection(ungroup=false):void {if(!selections.length||!canEditSelection())return;edit(()=>{const id=uid();for(const s of selections){const item=entity(level(),s)!;if(ungroup)delete item.groupId;else item.groupId=id;}});status(ungroup?'Đã tách nhóm.':'Đã nhóm vật và vùng. Alt+bấm để chỉnh riêng một thành phần.');}
function frameSelection():void {if(playing)return;if(!selections.length){fit();return;}const b=selectionBounds(project,level(),selections);view.zoom=Math.max(.05,Math.min(2,(viewport.clientWidth-80)/Math.max(1,b.w),(viewport.clientHeight-80)/Math.max(1,b.h)));view.x=viewport.clientWidth/2-(b.left+b.w/2)*view.zoom;view.y=viewport.clientHeight/2-(b.top+b.h/2)*view.zoom;el<HTMLInputElement>('zoom').value=String(Math.round(view.zoom*100)/100);updateCoordinates();}
function copySelection():void {if(!selections.length)return;clipboard=capturePrefab(project,level(),selections,'Bản sao chọn');status('Đã sao chép. Ctrl+V đặt cụm tại tâm khung nhìn.');}
function pasteSelection():void {const copied=clipboard;if(!copied)return;edit(()=>setSelection(instantiatePrefab(project,level(),copied,snapped({x:(viewport.clientWidth/2-view.x)/view.zoom,y:(viewport.clientHeight/2-view.y)/view.zoom}))));}
function engineUi():void {
  const a=project.assets.find(a=>a.id===chosenAsset),categories=[['terrain','Nền / tile'],['building','Công trình'],['nature','Thiên nhiên'],['prop','Đạo cụ'],['other','Khác']],kinds=[['ground','Nền'],['decor','Trang trí thấp'],['depth','Theo chân'],['cover','Tán / mái']];
  const field=(key:string,label:string,value:unknown,type='text')=>`<label class="form-row">${label}<input data-asset-prop="${key}" type="${type}" value="${esc(value)}" /></label>`;
  const select=(key:string,label:string,value:string,options:string[][])=>`<label class="form-row">${label}<select data-asset-prop="${key}">${options.map(([id,name])=>`<option value="${id}" ${id===value?'selected':''}>${name}</option>`).join('')}</select></label>`;
  el('asset-settings').innerHTML=a?`<p>${a.width} × ${a.height} · ${a.parts.length} part</p>${a.extraction?`<p class="hint">Cắt từ ${esc(a.extraction.sourceName)} · (${a.extraction.bounds.x}, ${a.extraction.bounds.y}) · ${a.extraction.shape}. Ảnh nguồn giữ nguyên.</p>`:''}`+field('name','Tên asset',a.name)+select('category','Phân loại',a.category??'other',categories)+select('defaultLayer','Layer khi chọn asset',a.defaultLayer??'depth',kinds)+`<div class="form-pair">${field('pivotX','Pivot X',a.pivot.x,'number')}${field('pivotY','Pivot Y',a.pivot.y,'number')}</div><p class="hint">Pivot thư viện dùng cho instance chưa ghi đè. Part mới phải cùng cỡ canvas.</p>`+a.parts.map((part,i)=>`<div class="part-row"><label><input type="checkbox" data-part-cover="${part.id}" ${part.cover?'checked':''} /> Part ${i+1} · phần che</label><div class="library-actions"><button data-replace-part="${part.id}">Thay ảnh</button><button data-remove-part="${part.id}" ${a.parts.length===1?'disabled':''}>Xóa part</button></div></div>`).join(''):'<p class="hint">Chọn asset trong thư viện để chỉnh tên, phân loại, pivot và part.</p>';
  el('prefabs').innerHTML=(project.prefabs??[]).map(f=>`<div class="prefab-row"><button data-place-prefab="${f.id}">${esc(f.name)} · ${f.objects.length} vật / ${f.regions.length} vùng</button><button data-remove-prefab="${f.id}" title="Xóa mẫu prefab">×</button></div>`).join('')||'<p class="hint">Chọn các vật/vùng rồi Lưu chọn. Prefab được lưu trong dự án và thư viện xuất.</p>';
  for(const id of ['select-all','group','ungroup','align','save-prefab','import-library','import-tileset','asset-category','import-asset','brush-step','tile-width','tile-height','prefab-name'])el<HTMLInputElement|HTMLButtonElement>(id).disabled=playing;
  for(const id of ['import-part','remove-asset'])el<HTMLInputElement|HTMLButtonElement>(id).disabled=playing||!a;
  el('asset-settings').querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('input,select,button').forEach(n=>{if(playing)n.disabled=true;});el('prefabs').querySelectorAll<HTMLButtonElement>('button').forEach(n=>n.disabled=playing);
}
el('select-all').addEventListener('click',selectAll);el('frame-selection').addEventListener('click',frameSelection);el('group').addEventListener('click',()=>groupSelection());el('ungroup').addEventListener('click',()=>groupSelection(true));
el('align').addEventListener('click',()=>{if(canEditSelection())edit(()=>alignEntities(project,level(),selections,el<HTMLSelectElement>('alignment').value as Alignment));});
el('save-prefab').addEventListener('click',()=>{if(!selections.length){status('Chọn các vật/vùng cần lưu thành prefab.');return;}edit(()=>{project.prefabs??=[];project.prefabs.push(capturePrefab(project,level(),selections,el<HTMLInputElement>('prefab-name').value.trim().slice(0,120)||'Cụm mới'));});});
el('prefabs').addEventListener('click',e=>{const place=(e.target as HTMLElement).closest<HTMLElement>('[data-place-prefab]'),remove=(e.target as HTMLElement).closest<HTMLElement>('[data-remove-prefab]');if(place){chosenPrefab=place.dataset.placePrefab!;chosenAsset='';setTool('prefab');ui();status('Bấm vào map để đặt prefab; giữ hình và các vùng cùng vị trí.');}else if(remove)edit(()=>project.prefabs=project.prefabs?.filter(f=>f.id!==remove.dataset.removePrefab));});
el('asset-category').addEventListener('change',palette);
el('asset-settings').addEventListener('change',e=>{const n=e.target as HTMLInputElement,key=n.dataset.assetProp,a=project.assets.find(a=>a.id===chosenAsset);if(!a)return;edit(()=>{if(n.dataset.partCover){a.parts.find(p=>p.id===n.dataset.partCover)!.cover=n.checked;}else if(key==='pivotX'||key==='pivotY')a.pivot[key==='pivotX'?'x':'y']=Number(n.value);else if(key)(a as any)[key]=n.value;});});
el<HTMLInputElement>('import-part').addEventListener('change',async e=>{const n=e.target as HTMLInputElement,a=project.assets.find(a=>a.id===chosenAsset);try{if(!playing&&a&&n.files?.[0]){const {url,image:img}=await readAssetImage(n.files[0]);if(img.width!==a.width||img.height!==a.height)throw new Error('Part phải cùng kích thước canvas với asset.');if(a.parts.length>=8)throw new Error('Asset tối đa 8 part.');const next=structuredClone(project),part={id:uid(),file:url,cover:true};next.assets.find(v=>v.id===a.id)!.parts.push(part);await loadAssets(next);edit(()=>project.assets.find(v=>v.id===a.id)!.parts.push(part));status('Đã thêm part che. Các part dùng chung canvas/pivot.');}}catch(error){status(String(error));}n.value='';});
el('asset-settings').addEventListener('click',e=>{if(playing)return;const a=project.assets.find(a=>a.id===chosenAsset),replace=(e.target as HTMLElement).closest<HTMLElement>('[data-replace-part]'),remove=(e.target as HTMLElement).closest<HTMLElement>('[data-remove-part]');if(!a)return;if(replace){replacingPart={assetId:a.id,partId:replace.dataset.replacePart!};el<HTMLInputElement>('replace-part').click();}else if(remove&&a.parts.length>1){edit(()=>a.parts=a.parts.filter(p=>p.id!==remove.dataset.removePart));void loadAssets().then(palette);}});
el<HTMLInputElement>('replace-part').addEventListener('change',async e=>{const n=e.target as HTMLInputElement,pending=replacingPart;replacingPart=null;try{const a=project.assets.find(a=>a.id===pending?.assetId);if(!playing&&pending&&a&&n.files?.[0]){const {url,image:img}=await readAssetImage(n.files[0]);if(img.width!==a.width||img.height!==a.height)throw new Error('Ảnh thay thế phải giữ kích thước canvas; vị trí instance và pivot được giữ.');const next=structuredClone(project);next.assets.find(a=>a.id===pending.assetId)!.parts.find(p=>p.id===pending.partId)!.file=url;await loadAssets(next);edit(()=>project.assets.find(a=>a.id===pending.assetId)!.parts.find(p=>p.id===pending.partId)!.file=url);status('Đã thay ảnh của part; các vị trí và vùng hoạt động được giữ.');}}catch(error){status(String(error));}n.value='';});
el('remove-asset').addEventListener('click',()=>{const id=chosenAsset;if(project.levels.some(l=>l.objects.some(o=>o.assetId===id))||project.prefabs?.some(f=>f.objects.some(o=>o.assetId===id))){status('Asset đang được dùng trong level/prefab. Xóa hoặc thay instance trước.');return;}edit(()=>{project.assets=project.assets.filter(a=>a.id!==id);chosenAsset='';});});
el('export-library').addEventListener('click',()=>download(`${project.id}.assets.json`,exportAssetLibrary(project)));
el<HTMLInputElement>('import-library').addEventListener('change',async e=>{const n=e.target as HTMLInputElement;try{if(!playing&&n.files?.[0]){if(n.files[0].size>20*1024*1024)throw new Error('Thư viện vượt 20 MB.');const next=mergeAssetLibrary(project,JSON.parse(await n.files[0].text()));await loadAssets(next);edit(()=>project=next);status('Đã nhập thư viện và prefab; các level hiện tại được giữ.');}}catch(error){status(String(error));}n.value='';});
function validate():ReturnType<typeof auditProject> {studio.openDock('review');const issues=auditProject(project);el('issues').innerHTML=issues.length?issues.map(i=>`<button class="issue ${i.severity}" data-issue-level="${i.levelId}" ${i.entity?`data-issue-id="${i.entity.id}" data-issue-kind="${i.entity.kind}"`:''}>${esc(project.levels.find(l=>l.id===i.levelId)?.name)} · ${esc(i.message)}</button>`).join(''):'<p class="hint">Không có lỗi Spawn, vùng hoặc cửa nối. ART/bố cục vẫn cần bạn đánh giá.</p>';status(`Kiểm level: ${issues.filter(i=>i.severity==='error').length} lỗi, ${issues.filter(i=>i.severity==='warning').length} lưu ý.`);return issues;}
el('validate').addEventListener('click',validate);el('export-runtime').addEventListener('click',()=>{try{validate();download(`${project.id}.runtime.json`,exportRuntimeProject(project));status('Đã xuất runtime: hình, vùng hoạt động và luồng level.');}catch(error){status(String(error));}});
el('issues').addEventListener('click',e=>{if(playing)return;const b=(e.target as HTMLElement).closest<HTMLElement>('[data-issue-level]');if(!b)return;if(!project.levels.some(l=>l.id===b.dataset.issueLevel)){el('issues').innerHTML='<p class="hint">Dữ liệu đã đổi. Bấm Kiểm tra để cập nhật.</p>';return;}activate(b.dataset.issueLevel!);if(b.dataset.issueId){editDomain=b.dataset.issueKind==='region'?'navigation':'scene';choose({kind:b.dataset.issueKind as 'object'|'region',id:b.dataset.issueId});ui();frameSelection();}else{zoomTo(1);view.x=viewport.clientWidth/2-level().spawn.x;view.y=viewport.clientHeight/2-level().spawn.y;}});
function minimapTransform(){const c=el<HTMLCanvasElement>('minimap'),l=level(),scale=Math.min(c.width/l.width,c.height/l.height);return {c,l,scale,x:(c.width-l.width*scale)/2,y:(c.height-l.height*scale)/2};}
function drawMinimap():void {const {c,l,scale,x,y}=minimapTransform(),m=c.getContext('2d')!;m.setTransform(1,0,0,1,0,0);m.clearRect(0,0,c.width,c.height);m.translate(x,y);m.scale(scale,scale);m.fillStyle=l.background;m.fillRect(0,0,l.width,l.height);for(const o of l.objects){const layer=l.layers.find(l=>l.id===o.layerId);if(!layer||(playing?!layer.enabled:!layer.visible))continue;const a=project.assets.find(a=>a.id===o.assetId)!,b=bounds(o,a);m.fillStyle=a.category==='terrain'?'#9baa72':'#54735b';m.fillRect(b.left,b.top,b.w,b.h);}for(const r of l.regions){m.beginPath();r.points.forEach((p,i)=>i?m.lineTo(p.x,p.y):m.moveTo(p.x,p.y));m.closePath();m.fillStyle=regionActivity(l,r)!=='active'?'#8994a244':r.kind==='block'?'#b65c5088':r.kind==='portal'?'#8b5ee7aa':'#6eb58744';m.fill();}m.strokeStyle='#fff';m.lineWidth=1/scale;m.strokeRect(-view.x/view.zoom,-view.y/view.zoom,viewport.clientWidth/view.zoom,viewport.clientHeight/view.zoom);m.fillStyle='#3266c4';m.beginPath();m.arc(playing?player.x:l.spawn.x,playing?player.y:l.spawn.y,3/scale,0,Math.PI*2);m.fill();}
el('minimap').addEventListener('pointerdown',e=>{if(playing)return;const {c,scale,x,y}=minimapTransform(),b=c.getBoundingClientRect(),wx=((e.clientX-b.left)*c.width/b.width-x)/scale,wy=((e.clientY-b.top)*c.height/b.height-y)/scale;view.x=viewport.clientWidth/2-wx*view.zoom;view.y=viewport.clientHeight/2-wy*view.zoom;});
const studio=setupStudio({setTool,setDomain,validate,settings:()=>{clearSelection();setTool('select');ui();}});
function refreshStudio():void {if(project){el<HTMLButtonElement>('cut-map').disabled=playing||!project.assets.length;el<HTMLButtonElement>('cut-asset').disabled=playing||!project.assets.some(a=>a.id===chosenAsset);el<HTMLButtonElement>('duplicate-asset').disabled=playing||project.assets.length>=200||!project.assets.some(a=>a.id===chosenAsset);el('duplicate-asset').title=project.assets.length>=200?'Thư viện đã đủ 200 asset':'Tạo bản sao độc lập trong thư viện (Ctrl+D)';}if(project)studio.refresh({project,tool,playing,selections,chosenAsset,draftVertices:draft.length,editDomain,inspectorContext,activeLayer});}
el('asset-background').addEventListener('click',()=>{const asset=project.assets.find(a=>a.id===chosenAsset),ground=level().layers.find(l=>l.kind==='ground'),cover=level().layers.find(l=>l.kind==='cover');if(!asset||playing)return;if(!ground||!cover||ground.locked||(asset.parts.some(p=>p.cover)&&cover.locked)){status('Mở khóa layer Nền và Tán/mái trước khi đặt nền.');return;}const applied=edit(()=>{const l=level();const existing=l.objects.find(o=>o.assetId===asset.id&&o.layerId===ground.id&&o.x===0&&o.y===0);if(existing&&(existing.locked||existing.groupId))throw new Error('Nền đang khóa hoặc thuộc cụm. Mở khóa / tách nhóm trước.');activeLayer=ground.id;const o=existing??stamp(asset.id,{x:0,y:0});if(!o)throw new Error('Không đặt được nền.');o.layerId=ground.id;o.pivot={x:0,y:0};o.scale=1;o.flipX=false;activeLayer=ground.id;l.width=Math.max(64,asset.width);l.height=Math.max(64,asset.height);l.spawn={x:Math.min(l.width-8,Math.max(8,l.spawn.x)),y:Math.min(l.height-8,Math.max(8,l.spawn.y))};choose({kind:'object',id:o.id});});if(!applied)return;setTool('select');fit();ui();status('Đã đặt nền tại 0,0 và khớp cỡ level. Các vật / vùng khác giữ nguyên; Ctrl+Z để hoàn tác.');});
el('duplicate-asset').addEventListener('click',()=>{try{cloneLibraryAsset();}catch(error){status((error as Error).message);}});
const assetCut=setupAssetCut({
  backup:source=>cloneLibraryAsset(source.id,false),
  assets:()=>project.assets,
  context:(id?:string)=>{
    const current=object(),background=[...level().objects].filter(o=>level().layers.some(l=>l.id===o.layerId&&l.kind==='ground')).sort((a,b)=>{const aa=project.assets.find(v=>v.id===a.assetId)!,bb=project.assets.find(v=>v.id===b.assetId)!;return bb.width*bb.height-aa.width*aa.height;})[0];
    const asset=project.assets.find(a=>a.id===(id??(current?.assetId||(inspectorContext==='asset'?chosenAsset:'')||background?.assetId||chosenAsset)))??[...project.assets].sort((a,b)=>b.width*b.height-a.width*a.height)[0];
    if(!asset)return;const source=current?.assetId===asset.id?current:background?.assetId===asset.id?background:level().objects.find(o=>o.assetId===asset.id);
    return {asset:structuredClone(asset),...(source?{object:structuredClone(source)}:{})};
  },
  image:file=>{const loaded=images.get(file);if(!loaded)throw new Error('Ảnh nguồn chưa nạp.');return loaded.image;},status,
  add:async(asset,source,place)=>{
    if(playing)throw new Error('Dừng Test để cắt asset.');if(project.assets.length>=200)throw new Error('Thư viện tối đa 200 asset.');
    const next=structuredClone(project),l=next.levels.find(v=>v.id===next.activeLevelId)!;next.assets.push(asset);let placed:EditorObject|undefined;
    if(place){const o=l.objects.find(o=>o.id===source.object?.id),base=l.layers.find(v=>v.kind===asset.defaultLayer),cover=l.layers.find(v=>v.kind==='cover');if(!o||o.assetId!==source.asset.id)throw new Error('Không còn instance nguồn trong level.');if(!base||!cover||base.locked||(asset.parts.some(p=>p.cover)&&cover.locked))throw new Error('Mở khóa layer đích trước khi đặt bản cắt, hoặc bỏ chọn Đặt bản cắt.');if(l.objects.length>=10000)throw new Error('Level tối đa 10000 instance.');placed={id:uid(),name:asset.name,assetId:asset.id,layerId:base.id,coverLayerId:cover.id,...cutPlacement(source.asset,o,asset.extraction!.bounds,asset.pivot),scale:o.scale,flipX:o.flipX,opacity:o.opacity,locked:false};l.objects.push(placed);}
    const validated=parseProject(next);await loadAssets(validated);setDomain('scene');
    if(!edit(()=>{project=validated;chosenAsset=asset.id;chosenPrefab='';if(placed){choose({kind:'object',id:placed.id},false,true);activeLayer=placed.layerId;}else{clearSelection();inspectorContext='asset';}}))throw new Error('Không thêm được asset vào dự án.');
    setTool('select');ui();
  }
});
el('cut-map').addEventListener('click',()=>{if(!playing)assetCut.open();});
el('cut-asset').addEventListener('click',()=>{if(!playing)assetCut.open(chosenAsset);});
Object.assign(window,{__mapEditorDiagnostics:()=>({ready,project:structuredClone(project),selected,selections:structuredClone(selections),chosenAsset,chosenPrefab,activeLayer,tool,editDomain,inspectorContext,draftVertices:draft.length,playing,player:{...player},view:{...view},undoCount:undo.length,redoCount:redo.length,alignmentGuides:[...alignmentGuides],validPlayer:ready&&playing?editorWalkable(level(),player):null})});
requestAnimationFrame(render);init().catch(error=>status(`Không nạp được editor: ${String(error)}. Chạy npm run assets rồi tải lại.`));
