function el<T extends HTMLElement = HTMLElement>(id: string): T {
  const element = document.getElementById(id);
  if (!element) throw new Error(`Thiếu thành phần ${id}.`);
  return element as T;
}

// Every DOM id used by the client. Look elements up here, not inside feature code.
export const dom = {
  stage: el('stage'),
  worldLabels: el('world-labels'),
  stageMessage: el('stage-message'),
  stageBadge: el('stage-badge'),
  stageCorner: el('stage-corner'),
  sceneKicker: el('scene-kicker'),
  sceneTitle: el('scene-title'),
  sceneTag: el('scene-tag'),
  positionReadout: el('position-readout'),
  renderReadout: el('render-readout'),
  thirdStat: el('third-stat'),
  thirdStatLabel: el('third-stat-label'),
  frameCounter: el('frame-counter'),
  frameName: el('frame-name'),
  movementHelp: el('movement-help'),
  movementNote: el('movement-note'),
  touchPad: el('touch-pad'),
  actorControls: el('actor-controls'),
  actorSelect: el<HTMLSelectElement>('actor'),
  actorNote: el('actor-note'),
  assetSource: el('asset-source'),
  animationControls: el('animation-controls'),
  motionSelect: el<HTMLSelectElement>('motion-state'),
  fpsInput: el<HTMLInputElement>('animation-fps'),
  fpsValue: el('fps-value'),
  gaitControl: el('gait-control'),
  gaitNote: el('gait-note'),
  strideInput: el<HTMLInputElement>('stride-distance'),
  strideValue: el('stride-value'),
  playButton: el<HTMLButtonElement>('play-pause'),
  frameBack: el<HTMLButtonElement>('previous-frame'),
  frameNext: el<HTMLButtonElement>('next-frame'),
  resetPosition: el<HTMLButtonElement>('reset-position'),
  movementControls: el('movement-controls'),
  speedInput: el<HTMLInputElement>('move-speed'),
  speedValue: el('speed-value'),
  actorCount: el<HTMLSelectElement>('actor-count'),
  backdrop: el<HTMLSelectElement>('backdrop'),
  showDebug: el<HTMLInputElement>('show-debug'),
  followControl: el('follow-control'),
  follow: el<HTMLInputElement>('follow-camera'),
  onlineControls: el('online-controls'),
  onlineRoster: el('online-roster'),
  playerList: el('player-list'),
  roomId: el('room-id'),
  connectionChip: el('connection-chip'),
  networkStatus: el('network-status'),
  nameInput: el<HTMLInputElement>('player-name'),
  avatarSelect: el<HTMLSelectElement>('avatar'),
  serverInput: el<HTMLInputElement>('server-url'),
  joinButton: el<HTMLButtonElement>('join-room'),
  leaveButton: el<HTMLButtonElement>('leave-room'),
  secondWindow: el<HTMLButtonElement>('second-window'),
};
